import React from 'react'
import { IconHome, IconLogin, IconUserPlus, IconAbc, IconSettings, IconUser, IconLogout } from '@tabler/icons-react'

const home = <IconHome />
const login = <IconLogin />
const register = <IconUserPlus />
const quiz = <IconAbc />
const settings = <IconSettings />
const user = <IconUser />
const logout = <IconLogout />

export const menuElements = [
	{ name: 'Strona główna', isNew: false, pathname: '/', icon: home },
	{ name: 'Quiz 1', isNew: false, pathname: '/quiz1', icon: quiz },
	{ name: 'Quiz 2', isNew: false, pathname: '/quiz2', icon: quiz },
	{ name: 'Quiz 3', isNew: true, pathname: '/quiz3', icon: quiz },
	{ name: 'Quiz 4', isNew: true, pathname: '/quiz4', icon: quiz },
	{ name: 'Quiz 5', isNew: true, pathname: '/quiz5', icon: quiz },
	{ name: 'Logowanie', isNew: false, pathname: '/logowanie', icon: login },
	{ name: 'Rejestracja', isNew: false, pathname: '/rejestracja', icon: register },
]
export const quizzes = [
	{ name: 'Technik Informatyk', isNew: false, pathname: '/quiz1', image: '/it.png' },
	{ name: 'Technik Kucharz', isNew: false, pathname: '/quiz2', image: '/cooker.png' },
	{ name: 'Technik Mechanik', isNew: true, pathname: '/quiz3', image: '/mechanic.png' },
	{ name: 'Aplikacja prawnicza', isNew: true, pathname: '/quiz4', image: '/judge.png' },
	{ name: 'Technik Hotelarstwa', isNew: true, pathname: '/quiz5', image: '/hotel.png' },
	{ name: 'Technik Dekarz', isNew: true, pathname: '/quiz5', image: '/roofer.png' },
]
export const userMenuElements = [
	{ name: 'Profil', pathname: '/profil', icon: settings },
	{ name: 'Ustawienia', pathname: '/ustawienia', icon: user },
	{ name: 'Wyloguj', pathname: '#', icon: logout },
]

export const learnTrick = [
	'Wyciszenie Telefonu: Warto wyciszyć lub wyłączyć telefon podczas nauki. Powiadomienia z mediów społecznościowych i wiadomości mogą być rozpraszające. Jeśli musisz korzystać z telefonu do nauki, wyłącz powiadomienia, aby skoncentrować się na materiale.',

	'Planowanie i Organizacja: Stwórz plan nauki, który obejmuje określone godziny i cele. Dzięki temu unikniesz chaosu i pozwolisz sobie na skupienie się na konkretnej dziedzinie w danym czasie.',

	'Zapisywanie Pytań: Wykorzystaj funkcję zapisywania pytań na których nie znasz odpowiedzi. To świetny sposób na śledzenie luk w Twojej wiedzy i późniejsze skoncentrowanie się na tych obszarach.',

	'Rozumienie Materiału: Nie ucz się na pamięć, ale staraj się zrozumieć materiał. Zamiast powtarzać tekst bezmyślnie, próbuj wyjaśnić go sobie w własnych słowach. To pomaga w lepszym zrozumieniu i utrwaleniu informacji.',

	'Variety in Learning: Urozmaicaj swoją naukę. Nie polegaj tylko na jednym źródle materiałów. Korzystaj z podręczników, notatek, konspektów, filmów, czy też aplikacji edukacyjnych.',

	'Przerwy i Regeneracja: Nie zapominaj o przerwach. Krótkie przerwy co godzinę pomagają zachować skoncentrowanie. Pamiętaj też o regularnym snu i odpowiednim odżywianiu.',

	'Ćwiczenia i Zdrowy Tryb Życia: Aktywność fizyczna ma ogromny wpływ na mózg. Staraj się regularnie ćwiczyć i dbać o zdrową dietę.',

	'Testowanie Siebie: Wykorzystuj testy i quizy do sprawdzania swojej wiedzy. To pomoże Ci ocenić, które obszary wymagają więcej uwagi.',

	'Nauczanie Innych: Spróbuj nauczyć kogoś innego materiału, który się uczysz. Nauczanie jest doskonałym sposobem na utrwalenie wiedzy.',

	'Motywacja i Pozytywne Myślenie: Zawsze pamiętaj o swoim celu i motywacji do nauki. Pozytywne myślenie może znacząco wpłynąć na Twoje wyniki.',
]

export const testimonials = [
	{
		id: 0,
		name: 'Wojtek K.',
		image: '/feedbakcFemale.png',
		text: 'NaukaQuizy4U to strona, która uratowała mi skórę! Gdy zbliżał się mój egzamin na poziomie B, poczułem się zdezorientowany ogromem materiału. Na szczęście, trafiłem na tę stronę, która oferowała losowanie zestawów pytań. To dało mi możliwość efektywnej nauki i skupienia się na słabych punktach. Rywalizacja z moimi kolegami była świetnym dodatkiem, który dodatkowo motywował mnie do nauki. Dzięki "NaukaQuizy4U" zdałem egzamin z doskonałym wynikiem, a teraz polecam ją każdemu, kto potrzebuje pomocy w nauce',
	},
	{
		id: 1,
		name: 'Anna S.',
		image: '/feedbakcMale.png',
		text: 'NaukaQuizy4U to moje tajne narzędzie do sukcesów na egzaminach! Dzięki tej stronie, którą odkryłam niedawno, miałam dostęp do praktycznych quizów, które świetnie przygotowały mnie do egzaminu na poziomie C. Losowanie jednego pytania po drugim było dla mnie niesamowicie pomocne, ponieważ mogłam skupić się na zagadnieniach, które sprawiały mi najwięcej problemów. Efekty? Zdałam egzamin z wysokim wynikiem! Polecam każdemu, kto potrzebuje solidnej nauki',
	},
]

export const faq = [
	{
		title: 'Czym jest Quizy4U?',
		answer:
			'Quizy4U to platforma oferująca quizy przygotowane specjalnie do różnych egzaminów na różnych szczeblach nauki. Uczniowie i studenci mogą korzystać z naszych quizów, aby doskonalić swoją wiedzę i przygotować się do egzaminów.',
	},
	{
		title: 'Jakie rodzaje quizów oferujemy?',
		answer:
			'Nasza platforma umożliwia dostęp do różnych rodzajów quizów, takich jak losowanie jednego pytania, zestaw 40 pytań do samodzielnego rozwiązania czy też niestandardowe zestawy pytań wybrane przez użytkownika. Możesz także wydrukować test z losowo wybranymi pytaniami.',
	},
	{
		title: 'Jak działa opcja rywalizacji z przyjaciółmi?',
		answer:
			'Na Quizy4U możesz utworzyć pokój i zaprosić swoich znajomych do rywalizacji. Każdy z was będzie mógł rozwiązywać te same quizy, a wyniki zostaną porównane. To świetny sposób na wspólną naukę i rywalizację.',
	},
	{
		title: 'Co to jest funkcja zapisywania pytań?',
		answer:
			'Jeśli napotkasz pytania, na które nie znasz odpowiedzi, możesz je zapisać na swoim koncie. Później będziesz mógł stworzyć z nich własny test, aby się do nich przygotować.',
	},
]

export const questions = [
	{
		id: 1,
		question: "Kto reżyserował film 'Lista Schindlera' z 1993 roku?",
		answerA: 'Martin Scorsese',
		answerB: 'Steven Spielberg',
		answerC: 'James Cameron',
		answerD: 'Christopher Nolan',
		correctAnswer: 'Steven Spielberg',
		quizID: 1,
	},
	{
		id: 2,
		question: "W którym filmie Arnold Schwarzenegger mówi słynne słowa 'I'll be back'?",
		answerA: 'Commando',
		answerB: 'Predator',
		answerC: 'Total Recall',
		answerD: 'The Terminator',
		correctAnswer: 'The Terminator',
		quizID: 1,
	},
	{
		id: 3,
		question: "Jak nazywa się statek kosmiczny w 'Gwiezdnych wojnach' pilotaowany przez Hana Solo?",
		answerA: 'Star Cruiser',
		answerB: 'Millennium Falcon',
		answerC: 'Death Star',
		answerD: 'Eagle 5',
		correctAnswer: 'Millennium Falcon',
		quizID: 1,
	},
	{
		id: 4,
		question: "Kto zagrał Jacka Dawsona w filmie 'Titanic'?",
		answerA: 'Leonardo DiCaprio',
		answerB: 'Brad Pitt',
		answerC: 'Johnny Depp',
		answerD: 'Tom Cruise',
		correctAnswer: 'Leonardo DiCaprio',
		quizID: 1,
	},
	{
		id: 5,
		question: 'Jaki film zdobył Oscara dla najlepszego filmu w 1995 roku?',
		answerA: 'Pulp Fiction',
		answerB: 'Forrest Gump',
		answerC: 'The Shawshank Redemption',
		answerD: 'Braveheart',
		correctAnswer: 'Forrest Gump',
		quizID: 1,
	},
	{
		id: 6,
		question: 'Który film nie został wyreżyserowany przez Quentina Tarantino?',
		answerA: 'Reservoir Dogs',
		answerB: 'Inglourious Basterds',
		answerC: 'Boogie Nights',
		answerD: 'Django Unchained',
		correctAnswer: 'Boogie Nights',
		quizID: 1,
	},
	{
		id: 7,
		question: "Która aktorka zagrała główną rolę w filmie 'Pretty Woman'?",
		answerA: 'Meg Ryan',
		answerB: 'Julia Roberts',
		answerC: 'Sandra Bullock',
		answerD: 'Nicole Kidman',
		correctAnswer: 'Julia Roberts',
		quizID: 1,
	},
	{
		id: 8,
		question: "Jak nazywa się fikcyjna kraina w 'Władcy Pierścieni'?",
		answerA: 'Hogwarts',
		answerB: 'Narnia',
		answerC: 'Middle-earth',
		answerD: 'Westeros',
		correctAnswer: 'Middle-earth',
		quizID: 1,
	},
	{
		id: 9,
		question: "Kto napisał muzykę do filmu 'Piraci z Karaibów'?",
		answerA: 'John Williams',
		answerB: 'Hans Zimmer',
		answerC: 'Ennio Morricone',
		answerD: 'James Horner',
		correctAnswer: 'Hans Zimmer',
		quizID: 1,
	},
	{
		id: 10,
		question: "Jaki jest prawdziwy zawód Jasona Bourne'a w serii 'Bourne'?",
		answerA: 'Policjant',
		answerB: 'Złodziej',
		answerC: 'Szpieg',
		answerD: 'Pisarz',
		correctAnswer: 'Szpieg',
		quizID: 1,
	},
	{
		id: 11,
		question: "Kto zagrał główną rolę w filmie 'Matrix'?",
		answerA: 'Tom Cruise',
		answerB: 'Keanu Reeves',
		answerC: 'Johnny Depp',
		answerD: 'Brad Pitt',
		correctAnswer: 'Keanu Reeves',
		quizID: 1,
	},
	{
		id: 12,
		question: "Który film przedstawia historię króla szkockiego, Williama Wallace'a?",
		answerA: 'Braveheart',
		answerB: 'Rob Roy',
		answerC: 'Highlander',
		answerD: 'King Arthur',
		correctAnswer: 'Braveheart',
		quizID: 1,
	},
	{
		id: 13,
		question: "W którym filmie Jim Carrey gra zaniedbanego bankiera, który otrzymuje 'wszechmoc'?",
		answerA: 'Yes Man',
		answerB: 'Liar Liar',
		answerC: 'Bruce Almighty',
		answerD: 'The Truman Show',
		correctAnswer: 'Bruce Almighty',
		quizID: 1,
	},
	{
		id: 14,
		question: 'Jaki film opowiada historię Edwarda, człowieka z nożycami zamiast rąk?',
		answerA: 'Edward Scissorhands',
		answerB: 'Sweeney Todd',
		answerC: 'The Nightmare Before Christmas',
		answerD: 'Corpse Bride',
		correctAnswer: 'Edward Scissorhands',
		quizID: 1,
	},
	{
		id: 15,
		question: 'Który z tych filmów nie jest filmem braci Coen?',
		answerA: 'Fargo',
		answerB: 'No Country for Old Men',
		answerC: 'The Big Lebowski',
		answerD: 'Memento',
		correctAnswer: 'Memento',
		quizID: 1,
	},
	{
		id: 16,
		question: "Kto reżyserował film 'Psychoza'?",
		answerA: 'Alfred Hitchcock',
		answerB: 'Stanley Kubrick',
		answerC: 'Steven Spielberg',
		answerD: 'Martin Scorsese',
		correctAnswer: 'Alfred Hitchcock',
		quizID: 1,
	},
	{
		id: 17,
		question: "Jak nazywa się pierwszy film z serii 'Gwiezdne Wojny' wydany w 1977 roku?",
		answerA: 'Nowa nadzieja',
		answerB: 'Imperium kontratakuje',
		answerC: 'Powrót Jedi',
		answerD: 'Mroczne widmo',
		correctAnswer: 'Nowa nadzieja',
		quizID: 1,
	},
	{
		id: 18,
		question: "Która aktorka zagrała główną rolę w filmie 'Czarny Łabędź'?",
		answerA: 'Mila Kunis',
		answerB: 'Natalie Portman',
		answerC: 'Keira Knightley',
		answerD: 'Scarlett Johansson',
		correctAnswer: 'Natalie Portman',
		quizID: 1,
	},
	{
		id: 19,
		question: 'Który film przedstawia historię króla Lwa o imieniu Simba?',
		answerA: 'Madagaskar',
		answerB: 'Król Lew',
		answerC: 'Zwierzogród',
		answerD: 'Księga dżungli',
		correctAnswer: 'Król Lew',
		quizID: 1,
	},
	{
		id: 20,
		question: 'Który film opowiada historię dwóch skazanych, którzy zaprzyjaźniają się w więzieniu Shawshank?',
		answerA: 'Skazani na Shawshank',
		answerB: 'Zielona mila',
		answerC: 'Ucieczka z Alcatraz',
		answerD: 'Papillon',
		correctAnswer: 'Skazani na Shawshank',
		quizID: 1,
	},
	{
		id: 21,
		question: "Kto zagrał główną rolę kobiecą u boku Leonardo DiCaprio w filmie 'Incepcja'?",
		answerA: 'Marion Cotillard',
		answerB: 'Ellen Page',
		answerC: 'Cate Blanchett',
		answerD: 'Kate Winslet',
		correctAnswer: 'Ellen Page',
		quizID: 1,
	},
	{
		id: 22,
		question: "Który film był pierwszym, który zdobył statuetkę Oscara w kategorii 'Najlepszy film animowany'?",
		answerA: 'Shrek',
		answerB: 'Toy Story',
		answerC: 'Lewy Król',
		answerD: 'Spirited Away',
		correctAnswer: 'Shrek',
		quizID: 1,
	},
	{
		id: 23,
		question: 'W którym filmie Russell Crowe gra rzymskiego generała pragnącego zemsty?',
		answerA: 'Gladiator',
		answerB: 'Master and Commander',
		answerC: 'Robin Hood',
		answerD: 'A Beautiful Mind',
		correctAnswer: 'Gladiator',
		quizID: 1,
	},
	{
		id: 24,
		question: "Jakie jest nazwisko postaci granej przez Johnny'ego Deppa w serii 'Piraci z Karaibów'?",
		answerA: 'Jack Sparrow',
		answerB: 'Will Turner',
		answerC: 'Barbossa',
		answerD: 'Davy Jones',
		correctAnswer: 'Jack Sparrow',
		quizID: 1,
	},
	{
		id: 25,
		question: 'Który film opowiada historię dziewczyny dołączającej do elitarnego zespołu cheerleaderek?',
		answerA: 'Mean Girls',
		answerB: 'Bring It On',
		answerC: 'Clueless',
		answerD: 'Pitch Perfect',
		correctAnswer: 'Bring It On',
		quizID: 1,
	},
	{
		id: 26,
		question: "Kto reżyserował kultowy film science-fiction 'Blade Runner'?",
		answerA: 'Ridley Scott',
		answerB: 'Steven Spielberg',
		answerC: 'George Lucas',
		answerD: 'James Cameron',
		correctAnswer: 'Ridley Scott',
		quizID: 1,
	},
	{
		id: 27,
		question: 'Który z tych aktorów zagrał postać Hulka?',
		answerA: 'Chris Hemsworth',
		answerB: 'Robert Downey Jr.',
		answerC: 'Mark Ruffalo',
		answerD: 'Chris Evans',
		correctAnswer: 'Mark Ruffalo',
		quizID: 1,
	},
	{
		id: 28,
		question: "Jaki jest podtytuł drugiego filmu z serii 'Harry Potter'?",
		answerA: 'Książę Półkrwi',
		answerB: 'Komnata Tajemnic',
		answerC: 'Zakon Feniksa',
		answerD: 'Więzień Azkabanu',
		correctAnswer: 'Komnata Tajemnic',
		quizID: 1,
	},
	{
		id: 29,
		question:
			'W którym filmie główną postacią jest superbohater noszący czerwony pelerynę, który nie może tolerować kryptonitu?',
		answerA: 'Spider-Man',
		answerB: 'Batman',
		answerC: 'Superman',
		answerD: 'Iron Man',
		correctAnswer: 'Superman',
		quizID: 1,
	},
	{
		id: 30,
		question: "Która aktorka zdobyła Oscara za najlepszą rolę pierwszoplanową w filmie 'Czarny łabędź'?",
		answerA: 'Angelina Jolie',
		answerB: 'Jennifer Lawrence',
		answerC: 'Natalie Portman',
		answerD: 'Emma Stone',
		correctAnswer: 'Natalie Portman',
		quizID: 1,
	},
	{
		id: 31,
		question:
			'Który film przedstawia historię ratowania żydowskich pracowników podczas Holocaustu przez niemieckiego biznesmena?',
		answerA: 'Lista Schindlera',
		answerB: 'Pianista',
		answerC: 'La vita è bella',
		answerD: 'Boyz n the Hood',
		correctAnswer: 'Lista Schindlera',
		quizID: 1,
	},
	{
		id: 32,
		question: "Jak nazywa się fikcyjna kraina w filmie 'Władca Pierścieni'?",
		answerA: 'Narnia',
		answerB: 'Hogwart',
		answerC: 'Śródziemie',
		answerD: 'Westeros',
		correctAnswer: 'Śródziemie',
		quizID: 1,
	},
	{
		id: 33,
		question: "Kto zagrał postać Tony'ego Starka, znanego również jako Iron Man?",
		answerA: 'Chris Evans',
		answerB: 'Robert Downey Jr.',
		answerC: 'Chris Hemsworth',
		answerD: 'Jeremy Renner',
		correctAnswer: 'Robert Downey Jr.',
		quizID: 1,
	},
	{
		id: 34,
		question: 'Który z tych filmów nie został wyreżyserowany przez Quentina Tarantino?',
		answerA: 'Pulp Fiction',
		answerB: 'Rezerwowe Psy',
		answerC: 'Fight Club',
		answerD: 'Bękarty wojny',
		correctAnswer: 'Fight Club',
		quizID: 1,
	},
	{
		id: 35,
		question: 'W którym filmie główną postacią jest archeolog poszukujący Zaginionej Arki?',
		answerA: 'Indiana Jones: Poszukiwacze zaginionej arki',
		answerB: 'Indiana Jones: Ostatnia krucjata',
		answerC: 'Indiana Jones: Królestwo kryształowej czaszki',
		answerD: 'Mumia',
		correctAnswer: 'Indiana Jones: Poszukiwacze zaginionej arki',
		quizID: 1,
	},
	{
		id: 36,
		question: 'Który film opowiada o wydarzeniach na statku Titanic w 1912 roku?',
		answerA: 'Wodny świat',
		answerB: 'Titanic',
		answerC: 'Statek widmo',
		answerD: 'Posejdon',
		correctAnswer: 'Titanic',
		quizID: 1,
	},
	{
		id: 37,
		question: "Kto zagrał postać Jacka Dawsona w filmie 'Titanic'?",
		answerA: 'Brad Pitt',
		answerB: 'Leonardo DiCaprio',
		answerC: 'Tom Cruise',
		answerD: 'Johnny Depp',
		correctAnswer: 'Leonardo DiCaprio',
		quizID: 1,
	},
	{
		id: 38,
		question: 'Który z tych filmów jest adaptacją powieści J.R.R. Tolkiena?',
		answerA: 'Gra o tron',
		answerB: 'Władca Pierścieni',
		answerC: 'Kroniki Narnii',
		answerD: 'Eragon',
		correctAnswer: 'Władca Pierścieni',
		quizID: 1,
	},
	{
		id: 39,
		question: 'Jakie miasto jest domem dla Batmana w filmach o tej postaci?',
		answerA: 'Metropolis',
		answerB: 'Gotham City',
		answerC: 'Central City',
		answerD: 'Star City',
		correctAnswer: 'Gotham City',
		quizID: 1,
	},
	{
		id: 40,
		question:
			'Który film przedstawia losy grupy astronautów próbujących powstrzymać ogromny asteroid przed uderzeniem w Ziemię?',
		answerA: 'Deep Impact',
		answerB: 'Armageddon',
		answerC: 'Apollo 13',
		answerD: 'Gravity',
		correctAnswer: 'Armageddon',
		quizID: 1,
	},
	{
		id: 41,
		question: "Która aktorka zagrała główną rolę w filmie 'Pretty Woman'?",
		answerA: 'Meg Ryan',
		answerB: 'Julia Roberts',
		answerC: 'Sandra Bullock',
		answerD: 'Nicole Kidman',
		correctAnswer: 'Julia Roberts',
		quizID: 1,
	},
	{
		id: 42,
		question: 'Który film został nagrodzony Oscarem za najlepszy film w 1994 roku?',
		answerA: 'Pulp Fiction',
		answerB: 'Forrest Gump',
		answerC: 'Skazani na Shawshank',
		answerD: 'Król Lew',
		correctAnswer: 'Forrest Gump',
		quizID: 1,
	},
	{
		id: 43,
		question: "Kto reżyserował film 'Szeregowiec Ryan'?",
		answerA: 'Steven Spielberg',
		answerB: 'Michael Bay',
		answerC: 'Christopher Nolan',
		answerD: 'James Cameron',
		correctAnswer: 'Steven Spielberg',
		quizID: 1,
	},
	{
		id: 44,
		question:
			"Jak nazywa się film, w którym postać grana przez Bruce'a Willisa podróżuje w czasie, aby zapobiec rozprzestrzenianiu się śmiertelnej choroby?",
		answerA: 'Looper',
		answerB: 'Armageddon',
		answerC: '12 małp',
		answerD: 'Szósty Zmysł',
		correctAnswer: '12 małp',
		quizID: 1,
	},
	{
		id: 45,
		question: 'Która z tych postaci nie pojawia się w uniwersum Marvela?',
		answerA: 'Batman',
		answerB: 'Iron Man',
		answerC: 'Thor',
		answerD: 'Czarna Wdowa',
		correctAnswer: 'Batman',
		quizID: 1,
	},
	{
		id: 46,
		question:
			'Jak nazywa się film opowiadający historię króla Szkocji, który prowadził swoich ludzi do walki o niepodległość od Anglii?',
		answerA: '300',
		answerB: 'Braveheart',
		answerC: 'Rob Roy',
		answerD: 'Highlander',
		correctAnswer: 'Braveheart',
		quizID: 1,
	},
	{
		id: 47,
		question: "W którym filmie Arnold Schwarzenegger mówi słynną kwestię 'I'll be back'?",
		answerA: 'Predator',
		answerB: 'Commando',
		answerC: 'Terminator',
		answerD: 'Total Recall',
		correctAnswer: 'Terminator',
		quizID: 1,
	},
	{
		id: 48,
		question: 'Który z tych filmów nie został wyreżyserowany przez Alfreda Hitchcocka?',
		answerA: 'Psychoza',
		answerB: 'Północ, północny zachód',
		answerC: 'Ptaki',
		answerD: 'Omen',
		correctAnswer: 'Omen',
		quizID: 1,
	},
	{
		id: 49,
		question:
			'Jaka postać filmowa jest znana z noszenia długiego płaszcza, kapelusza fedora i używania bata jako narzędzia?',
		answerA: 'Sherlock Holmes',
		answerB: 'James Bond',
		answerC: 'Indiana Jones',
		answerD: 'Rick Blaine',
		correctAnswer: 'Indiana Jones',
		quizID: 1,
	},
	{
		id: 50,
		question: "Kto zagrał rolę Golluma w serii filmów 'Władca Pierścieni'?",
		answerA: 'Elijah Wood',
		answerB: 'Ian McKellen',
		answerC: 'Andy Serkis',
		answerD: 'Viggo Mortensen',
		correctAnswer: 'Andy Serkis',
		quizID: 1,
	},
	{
		id: 51,
		question: 'Który film przedstawia historię królowej szachów, Beth Harmon?',
		answerA: 'Królowa gambitu',
		answerB: 'Szachista',
		answerC: 'Szach-mat',
		answerD: 'Królowa',
		correctAnswer: 'Królowa gambitu',
		quizID: 1,
	},
	{
		id: 52,
		question: 'Jak nazywa się film, w którym Leonardo DiCaprio gra oszusta, który fałszuje czeki?',
		answerA: 'Incepcja',
		answerB: 'Złap mnie, jeśli potrafisz',
		answerC: 'Wilczy z Wall Street',
		answerD: 'Wyspa tajemnic',
		correctAnswer: 'Złap mnie, jeśli potrafisz',
		quizID: 1,
	},
	{
		id: 53,
		question: 'Który film opowiada historię miłości między dwoma mężczyznami w stanie Wyoming?',
		answerA: 'Tajemnica Brokeback Mountain',
		answerB: 'Call Me by Your Name',
		answerC: 'Miłość Simon',
		answerD: 'Carol',
		correctAnswer: 'Tajemnica Brokeback Mountain',
		quizID: 1,
	},
	{
		id: 54,
		question: "Kto zagrał główną rolę w filmie 'Cast Away'?",
		answerA: 'Brad Pitt',
		answerB: 'Tom Hanks',
		answerC: 'George Clooney',
		answerD: 'Matt Damon',
		correctAnswer: 'Tom Hanks',
		quizID: 1,
	},
	{
		id: 55,
		question: 'Który film przedstawia historię młodej dziewczyny przechodzącej szkolenie, aby stać się zabójczynią?',
		answerA: 'Hanna',
		answerB: 'Salt',
		answerC: 'Red Sparrow',
		answerD: 'Kill Bill',
		correctAnswer: 'Hanna',
		quizID: 1,
	},
	{
		id: 56,
		question:
			'Jak nazywa się film, w którym bohaterowie muszą przeżyć w świecie, w którym stworzenia reagują na dźwięk?',
		answerA: 'Ciche miejsce',
		answerB: 'Bird Box',
		answerC: 'Słyszysz mnie?',
		answerD: 'Echo',
		correctAnswer: 'Ciche miejsce',
		quizID: 1,
	},
	{
		id: 57,
		question: "Kto reżyserował film 'Incepcja'?",
		answerA: 'Christopher Nolan',
		answerB: 'Steven Spielberg',
		answerC: 'Quentin Tarantino',
		answerD: 'David Fincher',
		correctAnswer: 'Christopher Nolan',
		quizID: 1,
	},
	{
		id: 58,
		question: 'Który film jest oparty na książce o młodym czarodzieju o imieniu Harry?',
		answerA: 'Harry Potter i Kamień Filozoficzny',
		answerB: 'Władca Pierścieni',
		answerC: 'Hobbit',
		answerD: 'Eragon',
		correctAnswer: 'Harry Potter i Kamień Filozoficzny',
		quizID: 1,
	},
	{
		id: 59,
		question: "Która aktorka zagrała Katniss Everdeen w 'Igrzyskach śmierci'?",
		answerA: 'Emma Watson',
		answerB: 'Jennifer Lawrence',
		answerC: 'Shailene Woodley',
		answerD: 'Kristen Stewart',
		correctAnswer: 'Jennifer Lawrence',
		quizID: 1,
	},
	{
		id: 60,
		question:
			'Jaki jest tytuł filmu, w którym grupa ludzi budzi się w tajemniczym pokoju, musząc rozwiązać zagadki, aby przeżyć?',
		answerA: 'Saw',
		answerB: 'Escape Room',
		answerC: 'Labirynt',
		answerD: 'Kostka',
		correctAnswer: 'Escape Room',
		quizID: 1,
	},
	{
		id: 61,
		question: "Który aktor zagrał Tony'ego Starka, znanego też jako Iron Man, w filmach Marvel Cinematic Universe?",
		answerA: 'Chris Evans',
		answerB: 'Robert Downey Jr.',
		answerC: 'Tom Holland',
		answerD: 'Chris Hemsworth',
		correctAnswer: 'Robert Downey Jr.',
		quizID: 1,
	},
	{
		id: 62,
		question: 'Który film opowiada o wojnie między ludźmi a maszynami, gdzie głównym bohaterem jest Neo?',
		answerA: 'Incepcja',
		answerB: 'Matrix',
		answerC: 'Tron: Dziedzictwo',
		answerD: 'Blade Runner',
		correctAnswer: 'Matrix',
		quizID: 1,
	},
	{
		id: 63,
		question:
			"Jak nazywa się film, w którym postać grana przez Russella Crowe'a, matematyk i ekonomista, boryka się ze schizofrenią?",
		answerA: 'Piękny umysł',
		answerB: 'Człowiek, który poznał nieskończoność',
		answerC: 'Teoria wszystkiego',
		answerD: 'Gra tajemnic',
		correctAnswer: 'Piękny umysł',
		quizID: 1,
	},
	{
		id: 64,
		question: 'Który film opowiada historię króla Szkocji, który staje na czele rebelii przeciwko tyranii angielskiej?',
		answerA: 'Robert Bruce',
		answerB: 'Król Artur',
		answerC: 'Outlaw King',
		answerD: 'Braveheart',
		correctAnswer: 'Braveheart',
		quizID: 1,
	},
	{
		id: 65,
		question:
			'Jak nazywa się film, w którym grupa badaczy naukowych podróżuje przez wormhole w przestrzeni, aby zapewnić przetrwanie ludzkości?',
		answerA: 'Interstellar',
		answerB: 'Grawitacja',
		answerC: 'The Martian',
		answerD: 'Europa Report',
		correctAnswer: 'Interstellar',
		quizID: 1,
	},
	{
		id: 66,
		question: "Kto zagrał główną rolę w filmie 'Wielki Gatsby' z 2013 roku?",
		answerA: 'Brad Pitt',
		answerB: 'Leonardo DiCaprio',
		answerC: 'Johnny Depp',
		answerD: 'George Clooney',
		correctAnswer: 'Leonardo DiCaprio',
		quizID: 1,
	},
	{
		id: 67,
		question: 'Który film przedstawia dwóch iluzjonistów rywalizujących ze sobą na początku XX wieku?',
		answerA: 'Prestiż',
		answerB: 'Iluzja',
		answerC: 'Now You See Me',
		answerD: 'Magic in the Moonlight',
		correctAnswer: 'Prestiż',
		quizID: 1,
	},
	{
		id: 68,
		question: 'Który z tych filmów został wyreżyserowany przez Martina Scorsese?',
		answerA: 'Mroczny Rycerz',
		answerB: 'Chłopiec w pasiastej piżamie',
		answerC: 'Wilczy z Wall Street',
		answerD: 'Ford v Ferrari',
		correctAnswer: 'Wilczy z Wall Street',
		quizID: 1,
	},
	{
		id: 69,
		question:
			'W którym filmie bohater używa specjalnie wyćwiczonej techniki marzeń sennych, aby kradnąć tajemnice korporacyjne?',
		answerA: 'Eternal Sunshine of the Spotless Mind',
		answerB: 'Lucy',
		answerC: 'Incepcja',
		answerD: 'Source Code',
		correctAnswer: 'Incepcja',
		quizID: 1,
	},
	{
		id: 70,
		question: 'Jak nazywa się film o grupie skazańców wysłanej na misję kosmiczną do czarnej dziury?',
		answerA: 'Alien: Covenant',
		answerB: 'Sunshine',
		answerC: 'Interstellar',
		answerD: 'High Life',
		correctAnswer: 'High Life',
		quizID: 1,
	},
	{
		id: 71,
		question:
			'Który film przedstawia historię grupy astronautów próbujących rozbroić bombę na pokładzie statku kosmicznego Icarus II?',
		answerA: 'Prometeusz',
		answerB: 'Sunshine',
		answerC: 'Ad Astra',
		answerD: 'Apollo 13',
		correctAnswer: 'Sunshine',
		quizID: 1,
	},
	{
		id: 72,
		question: 'W którym filmie rodzina stara się przetrwać w świecie pełnym potworów o nadwrażliwym słuchu?',
		answerA: 'Bird Box',
		answerB: 'Ciche miejsce',
		answerC: 'The Happening',
		answerD: 'War of the Worlds',
		correctAnswer: 'Ciche miejsce',
		quizID: 1,
	},
	{
		id: 73,
		question: 'Który film opowiada o podróży morskiej młodego chłopca i tygrysa o imieniu Richard Parker?',
		answerA: 'Życie Pi',
		answerB: 'Moby Dick',
		answerC: 'Old Man and the Sea',
		answerD: 'Cast Away',
		correctAnswer: 'Życie Pi',
		quizID: 1,
	},
	{
		id: 74,
		question: 'Jak nazywa się film, w którym grupa przyjaciół próbuje przetrwać noc w mieście pełnym zombie?',
		answerA: '28 dni później',
		answerB: 'World War Z',
		answerC: 'Shaun of the Dead',
		answerD: 'Zombieland',
		correctAnswer: 'Shaun of the Dead',
		quizID: 1,
	},
	{
		id: 75,
		question: 'Który film opowiada o artystce i handlarzu dzieł sztuki, którzy planują kradzież obrazu?',
		answerA: 'Thomas Crown Affair',
		answerB: 'Trick',
		answerC: 'The Italian Job',
		answerD: 'The Art of Stealing',
		correctAnswer: 'Thomas Crown Affair',
		quizID: 1,
	},
	{
		id: 76,
		question:
			'Jak nazywa się film, w którym grupa ludzi próbuje przetrwać po globalnej katastrofie, która niemal całkowicie zniszczyła ludzkość i zmusiła ich do życia pod wodą?',
		answerA: 'Deep Blue Sea',
		answerB: 'Waterworld',
		answerC: 'The Abyss',
		answerD: 'Atlantis',
		correctAnswer: 'Waterworld',
		quizID: 1,
	},
	{
		id: 77,
		question: 'Który film opowiada historię grupy żołnierzy walczących z obcymi podczas inwazji na Ziemię?',
		answerA: 'Starship Troopers',
		answerB: 'Edge of Tomorrow',
		answerC: 'Independence Day',
		answerD: 'War of the Worlds',
		correctAnswer: 'Starship Troopers',
		quizID: 1,
	},
	{
		id: 78,
		question: "Kto zagrał główną rolę w filmie 'John Wick'?",
		answerA: 'Jason Statham',
		answerB: 'Keanu Reeves',
		answerC: 'Liam Neeson',
		answerD: 'Bruce Willis',
		correctAnswer: 'Keanu Reeves',
		quizID: 1,
	},
	{
		id: 79,
		question:
			'W którym filmie młoda kobieta musi przetrwać w świecie, gdzie większość ludzkości została zamieniona w zombie przez grzybową infekcję?',
		answerA: '28 dni później',
		answerB: 'World War Z',
		answerC: 'Resident Evil',
		answerD: 'The Girl with All the Gifts',
		correctAnswer: 'The Girl with All the Gifts',
		quizID: 1,
	},
	{
		id: 80,
		question:
			'Który film przedstawia historię nastoletniego chłopca, który odkrywa, że jest półbogiem, synem Posejdona?',
		answerA: 'Hercules',
		answerB: 'Percy Jackson & the Olympians: The Lightning Thief',
		answerC: 'Clash of the Titans',
		answerD: 'Immortals',
		correctAnswer: 'Percy Jackson & the Olympians: The Lightning Thief',
		quizID: 1,
	},
	{
		id: 81,
		question: 'W którym filmie bogaty ekscentryk zaprasza grupę badaczy na wyspę pełną klonowanych dinozaurów?',
		answerA: 'Godzilla',
		answerB: 'Jurassic Park',
		answerC: 'King Kong',
		answerD: 'The Lost World',
		correctAnswer: 'Jurassic Park',
		quizID: 1,
	},
	{
		id: 82,
		question: 'Który film przedstawia podróż astronauty, który zostaje zostawiony na Marsie przez swoją załogę?',
		answerA: 'Interstellar',
		answerB: 'Gravity',
		answerC: 'The Martian',
		answerD: 'Moon',
		correctAnswer: 'The Martian',
		quizID: 1,
	},
	{
		id: 83,
		question: 'Który film opowiada o rodzinie superbohaterów, którzy muszą ukrywać swoje moce?',
		answerA: 'The Avengers',
		answerB: 'The Incredibles',
		answerC: 'X-Men',
		answerD: 'Fantastic Four',
		correctAnswer: 'The Incredibles',
		quizID: 1,
	},
	{
		id: 84,
		question: 'Jak nazywa się film, w którym główny bohater budzi się każdego dnia w tym samym dniu?',
		answerA: 'Deja Vu',
		answerB: 'Groundhog Day',
		answerC: 'Looper',
		answerD: "The Time Traveler's Wife",
		correctAnswer: 'Groundhog Day',
		quizID: 1,
	},
	{
		id: 85,
		question:
			'Który film przedstawia historię matematyka, który próbuje przewidzieć rynkowe trendy za pomocą skomplikowanego systemu?',
		answerA: 'A Beautiful Mind',
		answerB: 'The Imitation Game',
		answerC: 'Moneyball',
		answerD: 'Pi',
		correctAnswer: 'Pi',
		quizID: 1,
	},
	{
		id: 86,
		question:
			'Który film opowiada historię grupy ludzi, którzy wpadają w śpiączkę i wędrują do wspólnej świadomości snów?',
		answerA: 'Inception',
		answerB: 'The Cell',
		answerC: 'Paprika',
		answerD: 'The Science of Sleep',
		correctAnswer: 'Paprika',
		quizID: 1,
	},
	{
		id: 87,
		question: 'W którym filmie robot o imieniu WALL-E zakochuje się w innym robocie o nazwie EVE?',
		answerA: 'Robots',
		answerB: 'I, Robot',
		answerC: 'WALL-E',
		answerD: 'Short Circuit',
		correctAnswer: 'WALL-E',
		quizID: 1,
	},
	{
		id: 88,
		question:
			'Który film opowiada historię królowej Szkocji, Maria Stuart, i jej politycznej rywalizacji z królową Anglii, Elżbietą I?',
		answerA: 'Elizabeth',
		answerB: 'Mary Queen of Scots',
		answerC: 'The Other Boleyn Girl',
		answerD: 'The Favourite',
		correctAnswer: 'Mary Queen of Scots',
		quizID: 1,
	},
	{
		id: 89,
		question:
			'W którym filmie kierowca wyścigowy i konstruktor samochodowy łączą siły, aby pokonać dominujące włoskie firmy samochodowe?',
		answerA: 'Rush',
		answerB: 'Ford v Ferrari',
		answerC: 'Talladega Nights',
		answerD: 'Days of Thunder',
		correctAnswer: 'Ford v Ferrari',
		quizID: 1,
	},
	{
		id: 90,
		question:
			'Jak nazywa się film, w którym młody mężczyzna odkrywa, że jego ojciec, którego nigdy nie poznał, jest bogatym przedsiębiorcą?',
		answerA: 'The Pursuit of Happyness',
		answerB: 'The Secret Life of Walter Mitty',
		answerC: 'Big Fish',
		answerD: 'About a Boy',
		correctAnswer: 'Big Fish',
		quizID: 1,
	},
]
