import React from 'react'
import {
	IconHome,
	IconLogin,
	IconUserPlus,
	IconAbc,
	IconSettings,
	IconUser,
	IconLogout,
	IconDeviceFloppy,
	IconFiles,
} from '@tabler/icons-react'

const home = <IconHome />
const login = <IconLogin />
const register = <IconUserPlus />
const quiz = <IconAbc />
const settings = <IconSettings />
const user = <IconUser />
const logout = <IconLogout />
const savedQuestions = <IconDeviceFloppy />
const savedQuizzes = <IconFiles />

export const menuElements = [
	{ name: 'Strona główna', isNew: false, pathname: '/', icon: home },
	{ name: 'Quiz 1', isNew: false, pathname: '/quiz1', icon: quiz },
	{ name: 'Quiz 2', isNew: false, pathname: '/quiz2', icon: quiz },
	{ name: 'Quiz 3', isNew: true, pathname: '/quiz3', icon: quiz },
	{ name: 'Quiz 4', isNew: true, pathname: '/quiz4', icon: quiz },
	{ name: 'Quiz 5', isNew: true, pathname: '/quiz5', icon: quiz },
	{ name: 'Logowanie', isNew: false, pathname: '/logowanie', icon: login },
	{ name: 'Rejestracja', isNew: false, pathname: '/rejestracja', icon: register },
]
export const quizzes = [
	{ name: 'Technik Informatyk', isNew: false, pathname: '/quiz1', image: '/it.png' },
	{ name: 'Technik Kucharz', isNew: false, pathname: '/quiz2', image: '/cooker.png' },
	{ name: 'Technik Mechanik', isNew: true, pathname: '/quiz3', image: '/mechanic.png' },
	{ name: 'Aplikacja prawnicza', isNew: true, pathname: '/quiz4', image: '/judge.png' },
	{ name: 'Technik Hotelarstwa', isNew: true, pathname: '/quiz5', image: '/hotel.png' },
	{ name: 'Technik Dekarz', isNew: true, pathname: '/quiz5', image: '/roofer.png' },
]
export const userMenuElements = [
	{ name: 'Profil', pathname: '/profil', icon: user },
	{ name: 'Ustawienia', pathname: '/ustawienia', icon: settings },
	{ name: 'Zapisane pytania', pathname: '/zapisane-pytania', icon: savedQuestions },
	// { name: 'Zapisane quizy', pathname: '/zapisane-quizy', icon: savedQuizzes },
	{ name: 'Wyloguj', pathname: '#', icon: logout },
]

export const learnTrick = [
	'Wyciszenie Telefonu: Warto wyciszyć lub wyłączyć telefon podczas nauki. Powiadomienia z mediów społecznościowych i wiadomości mogą być rozpraszające. Jeśli musisz korzystać z telefonu do nauki, wyłącz powiadomienia, aby skoncentrować się na materiale.',

	'Planowanie i Organizacja: Stwórz plan nauki, który obejmuje określone godziny i cele. Dzięki temu unikniesz chaosu i pozwolisz sobie na skupienie się na konkretnej dziedzinie w danym czasie.',

	'Zapisywanie Pytań: Wykorzystaj funkcję zapisywania pytań na których nie znasz odpowiedzi. To świetny sposób na śledzenie luk w Twojej wiedzy i późniejsze skoncentrowanie się na tych obszarach.',

	'Rozumienie Materiału: Nie ucz się na pamięć, ale staraj się zrozumieć materiał. Zamiast powtarzać tekst bezmyślnie, próbuj wyjaśnić go sobie w własnych słowach. To pomaga w lepszym zrozumieniu i utrwaleniu informacji.',

	'Variety in Learning: Urozmaicaj swoją naukę. Nie polegaj tylko na jednym źródle materiałów. Korzystaj z podręczników, notatek, konspektów, filmów, czy też aplikacji edukacyjnych.',

	'Przerwy i Regeneracja: Nie zapominaj o przerwach. Krótkie przerwy co godzinę pomagają zachować skoncentrowanie. Pamiętaj też o regularnym snu i odpowiednim odżywianiu.',

	'Ćwiczenia i Zdrowy Tryb Życia: Aktywność fizyczna ma ogromny wpływ na mózg. Staraj się regularnie ćwiczyć i dbać o zdrową dietę.',

	'Testowanie Siebie: Wykorzystuj testy i quizy do sprawdzania swojej wiedzy. To pomoże Ci ocenić, które obszary wymagają więcej uwagi.',

	'Nauczanie Innych: Spróbuj nauczyć kogoś innego materiału, który się uczysz. Nauczanie jest doskonałym sposobem na utrwalenie wiedzy.',

	'Motywacja i Pozytywne Myślenie: Zawsze pamiętaj o swoim celu i motywacji do nauki. Pozytywne myślenie może znacząco wpłynąć na Twoje wyniki.',
]

export const testimonials = [
	{
		id: 0,
		name: 'Wojtek K.',
		image: '/feedbakcFemale.png',
		text: 'NaukaQuizy4U to strona, która uratowała mi skórę! Gdy zbliżał się mój egzamin na poziomie B, poczułem się zdezorientowany ogromem materiału. Na szczęście, trafiłem na tę stronę, która oferowała losowanie zestawów pytań. To dało mi możliwość efektywnej nauki i skupienia się na słabych punktach. Rywalizacja z moimi kolegami była świetnym dodatkiem, który dodatkowo motywował mnie do nauki. Dzięki "NaukaQuizy4U" zdałem egzamin z doskonałym wynikiem, a teraz polecam ją każdemu, kto potrzebuje pomocy w nauce',
	},
	{
		id: 1,
		name: 'Anna S.',
		image: '/feedbakcMale.png',
		text: 'NaukaQuizy4U to moje tajne narzędzie do sukcesów na egzaminach! Dzięki tej stronie, którą odkryłam niedawno, miałam dostęp do praktycznych quizów, które świetnie przygotowały mnie do egzaminu na poziomie C. Losowanie jednego pytania po drugim było dla mnie niesamowicie pomocne, ponieważ mogłam skupić się na zagadnieniach, które sprawiały mi najwięcej problemów. Efekty? Zdałam egzamin z wysokim wynikiem! Polecam każdemu, kto potrzebuje solidnej nauki',
	},
]

export const faq = [
	{
		title: 'Czym jest Quizy4U?',
		answer:
			'Quizy4U to platforma oferująca quizy przygotowane specjalnie do różnych egzaminów na różnych szczeblach nauki. Uczniowie i studenci mogą korzystać z naszych quizów, aby doskonalić swoją wiedzę i przygotować się do egzaminów.',
	},
	{
		title: 'Jakie rodzaje quizów oferujemy?',
		answer:
			'Nasza platforma umożliwia dostęp do różnych rodzajów quizów, takich jak losowanie jednego pytania, zestaw 40 pytań do samodzielnego rozwiązania czy też niestandardowe zestawy pytań wybrane przez użytkownika. Możesz także wydrukować test z losowo wybranymi pytaniami.',
	},
	{
		title: 'Jak działa opcja rywalizacji z przyjaciółmi?',
		answer:
			'Na Quizy4U możesz utworzyć pokój i zaprosić swoich znajomych do rywalizacji. Każdy z was będzie mógł rozwiązywać te same quizy, a wyniki zostaną porównane. To świetny sposób na wspólną naukę i rywalizację.',
	},
	{
		title: 'Co to jest funkcja zapisywania pytań?',
		answer:
			'Jeśli napotkasz pytania, na które nie znasz odpowiedzi, możesz je zapisać na swoim koncie. Później będziesz mógł stworzyć z nich własny test, aby się do nich przygotować.',
	},
]

export const questionsMovies = [
	{
		id: 1,
		question: "Kto reżyserował film 'Lista Schindlera' z 1993 roku?",
		answerA: 'Martin Scorsese',
		answerB: 'Steven Spielberg',
		answerC: 'James Cameron',
		answerD: 'Christopher Nolan',
		correctAnswer: 'answerB',
	},
	{
		id: 2,
		question: "W którym filmie Arnold Schwarzenegger mówi słynne słowa 'I'll be back'?",
		answerA: 'Commando',
		answerB: 'Predator',
		answerC: 'Total Recall',
		answerD: 'The Terminator',
		correctAnswer: 'answerD',
	},
	{
		id: 3,
		question: "Jak nazywa się statek kosmiczny w 'Gwiezdnych wojnach' pilotaowany przez Hana Solo?",
		answerA: 'Star Cruiser',
		answerB: 'Millennium Falcon',
		answerC: 'Death Star',
		answerD: 'Eagle 5',
		correctAnswer: 'answerB',
	},
	{
		id: 4,
		question: "Kto zagrał Jacka Dawsona w filmie 'Titanic'?",
		answerA: 'Leonardo DiCaprio',
		answerB: 'Brad Pitt',
		answerC: 'Johnny Depp',
		answerD: 'Tom Cruise',
		correctAnswer: 'answerA',
	},
	{
		id: 5,
		question: 'Jaki film zdobył Oscara dla najlepszego filmu w 1995 roku?',
		answerA: 'Pulp Fiction',
		answerB: 'Forrest Gump',
		answerC: 'The Shawshank Redemption',
		answerD: 'Braveheart',
		correctAnswer: 'answerB',
	},
	{
		id: 6,
		question: 'Który film nie został wyreżyserowany przez Quentina Tarantino?',
		answerA: 'Reservoir Dogs',
		answerB: 'Inglourious Basterds',
		answerC: 'Boogie Nights',
		answerD: 'Django Unchained',
		correctAnswer: 'answerC',
	},
	{
		id: 7,
		question: "Która aktorka zagrała główną rolę w filmie 'Pretty Woman'?",
		answerA: 'Meg Ryan',
		answerB: 'Julia Roberts',
		answerC: 'Sandra Bullock',
		answerD: 'Nicole Kidman',
		correctAnswer: 'answerB',
	},
	{
		id: 8,
		question: "Jak nazywa się fikcyjna kraina w 'Władcy Pierścieni'?",
		answerA: 'Hogwarts',
		answerB: 'Narnia',
		answerC: 'Middle-earth',
		answerD: 'Westeros',
		correctAnswer: 'answerC',
	},
	{
		id: 9,
		question: "Kto napisał muzykę do filmu 'Piraci z Karaibów'?",
		answerA: 'John Williams',
		answerB: 'Hans Zimmer',
		answerC: 'Ennio Morricone',
		answerD: 'James Horner',
		correctAnswer: 'answerB',
	},
	{
		id: 10,
		question: "Jaki jest prawdziwy zawód Jasona Bourne'a w serii 'Bourne'?",
		answerA: 'Policjant',
		answerB: 'Złodziej',
		answerC: 'Szpieg',
		answerD: 'Pisarz',
		correctAnswer: 'answerC',
	},
	{
		id: 11,
		question: "Kto zagrał główną rolę w filmie 'Matrix'?",
		answerA: 'Tom Cruise',
		answerB: 'Keanu Reeves',
		answerC: 'Johnny Depp',
		answerD: 'Brad Pitt',
		correctAnswer: 'answerB',
	},
	{
		id: 12,
		question: "Który film przedstawia historię króla szkockiego, Williama Wallace'a?",
		answerA: 'Braveheart',
		answerB: 'Rob Roy',
		answerC: 'Highlander',
		answerD: 'King Arthur',
		correctAnswer: 'answerA',
	},
	{
		id: 13,
		question: "W którym filmie Jim Carrey gra zaniedbanego bankiera, który otrzymuje 'wszechmoc'?",
		answerA: 'Yes Man',
		answerB: 'Liar Liar',
		answerC: 'Bruce Almighty',
		answerD: 'The Truman Show',
		correctAnswer: 'answerC',
	},
	{
		id: 14,
		question: 'Jaki film opowiada historię Edwarda, człowieka z nożycami zamiast rąk?',
		answerA: 'Edward Scissorhands',
		answerB: 'Sweeney Todd',
		answerC: 'The Nightmare Before Christmas',
		answerD: 'Corpse Bride',
		correctAnswer: 'answerA',
	},
	{
		id: 15,
		question: 'Który z tych filmów nie jest filmem braci Coen?',
		answerA: 'Fargo',
		answerB: 'No Country for Old Men',
		answerC: 'The Big Lebowski',
		answerD: 'Memento',
		correctAnswer: 'answerD',
	},
	{
		id: 16,
		question: "Kto reżyserował film 'Psychoza'?",
		answerA: 'Alfred Hitchcock',
		answerB: 'Stanley Kubrick',
		answerC: 'Steven Spielberg',
		answerD: 'Martin Scorsese',
		correctAnswer: 'answerA',
	},
	{
		id: 17,
		question: "Jak nazywa się pierwszy film z serii 'Gwiezdne Wojny' wydany w 1977 roku?",
		answerA: 'Nowa nadzieja',
		answerB: 'Imperium kontratakuje',
		answerC: 'Powrót Jedi',
		answerD: 'Mroczne widmo',
		correctAnswer: 'answerA',
	},
	{
		id: 18,
		question: "Która aktorka zagrała główną rolę w filmie 'Czarny Łabędź'?",
		answerA: 'Mila Kunis',
		answerB: 'Natalie Portman',
		answerC: 'Keira Knightley',
		answerD: 'Scarlett Johansson',
		correctAnswer: 'answerB',
	},
	{
		id: 19,
		question: 'Który film przedstawia historię króla Lwa o imieniu Simba?',
		answerA: 'Madagaskar',
		answerB: 'Król Lew',
		answerC: 'Zwierzogród',
		answerD: 'Księga dżungli',
		correctAnswer: 'answerB',
	},
	{
		id: 20,
		question: 'Który film opowiada historię dwóch skazanych, którzy zaprzyjaźniają się w więzieniu Shawshank?',
		answerA: 'Skazani na Shawshank',
		answerB: 'Zielona mila',
		answerC: 'Ucieczka z Alcatraz',
		answerD: 'Papillon',
		correctAnswer: 'answerA',
	},
	{
		id: 21,
		question: "Kto zagrał główną rolę kobiecą u boku Leonardo DiCaprio w filmie 'Incepcja'?",
		answerA: 'Marion Cotillard',
		answerB: 'Ellen Page',
		answerC: 'Cate Blanchett',
		answerD: 'Kate Winslet',
		correctAnswer: 'answerB',
	},
	{
		id: 22,
		question: "Który film był pierwszym, który zdobył statuetkę Oscara w kategorii 'Najlepszy film animowany'?",
		answerA: 'Shrek',
		answerB: 'Toy Story',
		answerC: 'Lewy Król',
		answerD: 'Spirited Away',
		correctAnswer: 'answerA',
	},
	{
		id: 23,
		question: 'W którym filmie Russell Crowe gra rzymskiego generała pragnącego zemsty?',
		answerA: 'Gladiator',
		answerB: 'Master and Commander',
		answerC: 'Robin Hood',
		answerD: 'A Beautiful Mind',
		correctAnswer: 'answerA',
	},
	{
		id: 24,
		question: "Jakie jest nazwisko postaci granej przez Johnny'ego Deppa w serii 'Piraci z Karaibów'?",
		answerA: 'Jack Sparrow',
		answerB: 'Will Turner',
		answerC: 'Barbossa',
		answerD: 'Davy Jones',
		correctAnswer: 'answerA',
	},
	{
		id: 25,
		question: 'Który film opowiada historię dziewczyny dołączającej do elitarnego zespołu cheerleaderek?',
		answerA: 'Mean Girls',
		answerB: 'Bring It On',
		answerC: 'Clueless',
		answerD: 'Pitch Perfect',
		correctAnswer: 'answerB',
	},
	{
		id: 26,
		question: "Kto reżyserował kultowy film science-fiction 'Blade Runner'?",
		answerA: 'Ridley Scott',
		answerB: 'Steven Spielberg',
		answerC: 'George Lucas',
		answerD: 'James Cameron',
		correctAnswer: 'answerA',
	},
	{
		id: 27,
		question: 'Który z tych aktorów zagrał postać Hulka?',
		answerA: 'Chris Hemsworth',
		answerB: 'Robert Downey Jr.',
		answerC: 'Mark Ruffalo',
		answerD: 'Chris Evans',
		correctAnswer: 'answerC',
	},
	{
		id: 28,
		question: "Jaki jest podtytuł drugiego filmu z serii 'Harry Potter'?",
		answerA: 'Książę Półkrwi',
		answerB: 'Komnata Tajemnic',
		answerC: 'Zakon Feniksa',
		answerD: 'Więzień Azkabanu',
		correctAnswer: 'answerB',
	},
	{
		id: 29,
		question:
			'W którym filmie główną postacią jest superbohater noszący czerwony pelerynę, który nie może tolerować kryptonitu?',
		answerA: 'Spider-Man',
		answerB: 'Batman',
		answerC: 'Superman',
		answerD: 'Iron Man',
		correctAnswer: 'answerC',
	},
	{
		id: 30,
		question: "Która aktorka zdobyła Oscara za najlepszą rolę pierwszoplanową w filmie 'Czarny łabędź'?",
		answerA: 'Angelina Jolie',
		answerB: 'Jennifer Lawrence',
		answerC: 'Natalie Portman',
		answerD: 'Emma Stone',
		correctAnswer: 'answerC',
	},
	{
		id: 31,
		question:
			'Który film przedstawia historię ratowania żydowskich pracowników podczas Holocaustu przez niemieckiego biznesmena?',
		answerA: 'Lista Schindlera',
		answerB: 'Pianista',
		answerC: 'La vita è bella',
		answerD: 'Boyz n the Hood',
		correctAnswer: 'answerA',
	},
	{
		id: 32,
		question: "Jak nazywa się fikcyjna kraina w filmie 'Władca Pierścieni'?",
		answerA: 'Narnia',
		answerB: 'Hogwart',
		answerC: 'Śródziemie',
		answerD: 'Westeros',
		correctAnswer: 'answerC',
	},
	{
		id: 33,
		question: "Kto zagrał postać Tony'ego Starka, znanego również jako Iron Man?",
		answerA: 'Chris Evans',
		answerB: 'Robert Downey Jr.',
		answerC: 'Chris Hemsworth',
		answerD: 'Jeremy Renner',
		correctAnswer: 'answerB',
	},
	{
		id: 34,
		question: 'Który z tych filmów nie został wyreżyserowany przez Quentina Tarantino?',
		answerA: 'Pulp Fiction',
		answerB: 'Rezerwowe Psy',
		answerC: 'Fight Club',
		answerD: 'Bękarty wojny',
		correctAnswer: 'answerC',
	},
	{
		id: 35,
		question: 'W którym filmie główną postacią jest archeolog poszukujący Zaginionej Arki?',
		answerA: 'Indiana Jones: Poszukiwacze zaginionej arki',
		answerB: 'Indiana Jones: Ostatnia krucjata',
		answerC: 'Indiana Jones: Królestwo kryształowej czaszki',
		answerD: 'Mumia',
		correctAnswer: 'answerA',
	},
	{
		id: 36,
		question: 'Który film opowiada o wydarzeniach na statku Titanic w 1912 roku?',
		answerA: 'Wodny świat',
		answerB: 'Titanic',
		answerC: 'Statek widmo',
		answerD: 'Posejdon',
		correctAnswer: 'answerB',
	},
	{
		id: 37,
		question: "Kto zagrał postać Jacka Dawsona w filmie 'Titanic'?",
		answerA: 'Brad Pitt',
		answerB: 'Leonardo DiCaprio',
		answerC: 'Tom Cruise',
		answerD: 'Johnny Depp',
		correctAnswer: 'answerB',
	},
	{
		id: 38,
		question: 'Który z tych filmów jest adaptacją powieści J.R.R. Tolkiena?',
		answerA: 'Gra o tron',
		answerB: 'Władca Pierścieni',
		answerC: 'Kroniki Narnii',
		answerD: 'Eragon',
		correctAnswer: 'answerB',
	},
	{
		id: 39,
		question: 'Jakie miasto jest domem dla Batmana w filmach o tej postaci?',
		answerA: 'Metropolis',
		answerB: 'Gotham City',
		answerC: 'Central City',
		answerD: 'Star City',
		correctAnswer: 'answerB',
	},
	{
		id: 40,
		question:
			'Który film przedstawia losy grupy astronautów próbujących powstrzymać ogromny asteroid przed uderzeniem w Ziemię?',
		answerA: 'Deep Impact',
		answerB: 'Armageddon',
		answerC: 'Apollo 13',
		answerD: 'Gravity',
		correctAnswer: 'answerB',
	},
	{
		id: 41,
		question: "Która aktorka zagrała główną rolę w filmie 'Pretty Woman'?",
		answerA: 'Meg Ryan',
		answerB: 'Julia Roberts',
		answerC: 'Sandra Bullock',
		answerD: 'Nicole Kidman',
		correctAnswer: 'answerB',
	},
	{
		id: 42,
		question: 'Który film został nagrodzony Oscarem za najlepszy film w 1994 roku?',
		answerA: 'Pulp Fiction',
		answerB: 'Forrest Gump',
		answerC: 'Skazani na Shawshank',
		answerD: 'Król Lew',
		correctAnswer: 'answerB',
	},
	{
		id: 43,
		question: "Kto reżyserował film 'Szeregowiec Ryan'?",
		answerA: 'Steven Spielberg',
		answerB: 'Michael Bay',
		answerC: 'Christopher Nolan',
		answerD: 'James Cameron',
		correctAnswer: 'answerA',
	},
	{
		id: 44,
		question:
			"Jak nazywa się film, w którym postać grana przez Bruce'a Willisa podróżuje w czasie, aby zapobiec rozprzestrzenianiu się śmiertelnej choroby?",
		answerA: 'Looper',
		answerB: 'Armageddon',
		answerC: '12 małp',
		answerD: 'Szósty Zmysł',
		correctAnswer: 'answerC',
	},
	{
		id: 45,
		question: 'Która z tych postaci nie pojawia się w uniwersum Marvela?',
		answerA: 'Batman',
		answerB: 'Iron Man',
		answerC: 'Thor',
		answerD: 'Czarna Wdowa',
		correctAnswer: 'answerA',
	},
	{
		id: 46,
		question:
			'Jak nazywa się film opowiadający historię króla Szkocji, który prowadził swoich ludzi do walki o niepodległość od Anglii?',
		answerA: '300',
		answerB: 'Braveheart',
		answerC: 'Rob Roy',
		answerD: 'Highlander',
		correctAnswer: 'answerB',
	},
	{
		id: 47,
		question: "W którym filmie Arnold Schwarzenegger mówi słynną kwestię 'I'll be back'?",
		answerA: 'Predator',
		answerB: 'Commando',
		answerC: 'Terminator',
		answerD: 'Total Recall',
		correctAnswer: 'answerC',
	},
	{
		id: 48,
		question: 'Który z tych filmów nie został wyreżyserowany przez Alfreda Hitchcocka?',
		answerA: 'Psychoza',
		answerB: 'Północ, północny zachód',
		answerC: 'Ptaki',
		answerD: 'Omen',
		correctAnswer: 'answerD',
	},
	{
		id: 49,
		question:
			'Jaka postać filmowa jest znana z noszenia długiego płaszcza, kapelusza fedora i używania bata jako narzędzia?',
		answerA: 'Sherlock Holmes',
		answerB: 'James Bond',
		answerC: 'Indiana Jones',
		answerD: 'Rick Blaine',
		correctAnswer: 'answerC',
	},
	{
		id: 50,
		question: "Kto zagrał rolę Golluma w serii filmów 'Władca Pierścieni'?",
		answerA: 'Elijah Wood',
		answerB: 'Ian McKellen',
		answerC: 'Andy Serkis',
		answerD: 'Viggo Mortensen',
		correctAnswer: 'answerC',
	},
	{
		id: 51,
		question: 'Który film przedstawia historię królowej szachów, Beth Harmon?',
		answerA: 'Królowa gambitu',
		answerB: 'Szachista',
		answerC: 'Szach-mat',
		answerD: 'Królowa',
		correctAnswer: 'answerA',
	},
	{
		id: 52,
		question: 'Jak nazywa się film, w którym Leonardo DiCaprio gra oszusta, który fałszuje czeki?',
		answerA: 'Incepcja',
		answerB: 'Złap mnie, jeśli potrafisz',
		answerC: 'Wilczy z Wall Street',
		answerD: 'Wyspa tajemnic',
		correctAnswer: 'answerB',
	},
	{
		id: 53,
		question: 'Który film opowiada historię miłości między dwoma mężczyznami w stanie Wyoming?',
		answerA: 'Tajemnica Brokeback Mountain',
		answerB: 'Call Me by Your Name',
		answerC: 'Miłość Simon',
		answerD: 'Carol',
		correctAnswer: 'answerA',
	},
	{
		id: 54,
		question: "Kto zagrał główną rolę w filmie 'Cast Away'?",
		answerA: 'Brad Pitt',
		answerB: 'Tom Hanks',
		answerC: 'George Clooney',
		answerD: 'Matt Damon',
		correctAnswer: 'answerB',
	},
	{
		id: 55,
		question: 'Który film przedstawia historię młodej dziewczyny przechodzącej szkolenie, aby stać się zabójczynią?',
		answerA: 'Hanna',
		answerB: 'Salt',
		answerC: 'Red Sparrow',
		answerD: 'Kill Bill',
		correctAnswer: 'answerA',
	},
	{
		id: 56,
		question:
			'Jak nazywa się film, w którym bohaterowie muszą przeżyć w świecie, w którym stworzenia reagują na dźwięk?',
		answerA: 'Ciche miejsce',
		answerB: 'Bird Box',
		answerC: 'Słyszysz mnie?',
		answerD: 'Echo',
		correctAnswer: 'answerA',
	},
	{
		id: 57,
		question: "Kto reżyserował film 'Incepcja'?",
		answerA: 'Christopher Nolan',
		answerB: 'Steven Spielberg',
		answerC: 'Quentin Tarantino',
		answerD: 'David Fincher',
		correctAnswer: 'answerA',
	},
	{
		id: 58,
		question: 'Który film jest oparty na książce o młodym czarodzieju o imieniu Harry?',
		answerA: 'Harry Potter i Kamień Filozoficzny',
		answerB: 'Władca Pierścieni',
		answerC: 'Hobbit',
		answerD: 'Eragon',
		correctAnswer: 'answerA',
	},
	{
		id: 59,
		question: "Która aktorka zagrała Katniss Everdeen w 'Igrzyskach śmierci'?",
		answerA: 'Emma Watson',
		answerB: 'Jennifer Lawrence',
		answerC: 'Shailene Woodley',
		answerD: 'Kristen Stewart',
		correctAnswer: 'answerB',
	},
	{
		id: 60,
		question:
			'Jaki jest tytuł filmu, w którym grupa ludzi budzi się w tajemniczym pokoju, musząc rozwiązać zagadki, aby przeżyć?',
		answerA: 'Saw',
		answerB: 'Escape Room',
		answerC: 'Labirynt',
		answerD: 'Kostka',
		correctAnswer: 'answerB',
	},
	{
		id: 61,
		question: "Który aktor zagrał Tony'ego Starka, znanego też jako Iron Man, w filmach Marvel Cinematic Universe?",
		answerA: 'Chris Evans',
		answerB: 'Robert Downey Jr.',
		answerC: 'Tom Holland',
		answerD: 'Chris Hemsworth',
		correctAnswer: 'answerB',
	},
	{
		id: 62,
		question: 'Który film opowiada o wojnie między ludźmi a maszynami, gdzie głównym bohaterem jest Neo?',
		answerA: 'Incepcja',
		answerB: 'Matrix',
		answerC: 'Tron: Dziedzictwo',
		answerD: 'Blade Runner',
		correctAnswer: 'answerB',
	},
	{
		id: 63,
		question:
			"Jak nazywa się film, w którym postać grana przez Russella Crowe'a, matematyk i ekonomista, boryka się ze schizofrenią?",
		answerA: 'Piękny umysł',
		answerB: 'Człowiek, który poznał nieskończoność',
		answerC: 'Teoria wszystkiego',
		answerD: 'Gra tajemnic',
		correctAnswer: 'answerA',
	},
	{
		id: 64,
		question: 'Który film opowiada historię króla Szkocji, który staje na czele rebelii przeciwko tyranii angielskiej?',
		answerA: 'Robert Bruce',
		answerB: 'Król Artur',
		answerC: 'Outlaw King',
		answerD: 'Braveheart',
		correctAnswer: 'answerD',
	},
	{
		id: 65,
		question:
			'Jak nazywa się film, w którym grupa badaczy naukowych podróżuje przez wormhole w przestrzeni, aby zapewnić przetrwanie ludzkości?',
		answerA: 'Interstellar',
		answerB: 'Grawitacja',
		answerC: 'The Martian',
		answerD: 'Europa Report',
		correctAnswer: 'answerA',
	},
	{
		id: 66,
		question: "Kto zagrał główną rolę w filmie 'Wielki Gatsby' z 2013 roku?",
		answerA: 'Brad Pitt',
		answerB: 'Leonardo DiCaprio',
		answerC: 'Johnny Depp',
		answerD: 'George Clooney',
		correctAnswer: 'answerB',
	},
	{
		id: 67,
		question: 'Który film przedstawia dwóch iluzjonistów rywalizujących ze sobą na początku XX wieku?',
		answerA: 'Prestiż',
		answerB: 'Iluzja',
		answerC: 'Now You See Me',
		answerD: 'Magic in the Moonlight',
		correctAnswer: 'answerA',
	},
	{
		id: 68,
		question: 'Który z tych filmów został wyreżyserowany przez Martina Scorsese?',
		answerA: 'Mroczny Rycerz',
		answerB: 'Chłopiec w pasiastej piżamie',
		answerC: 'Wilczy z Wall Street',
		answerD: 'Ford v Ferrari',
		correctAnswer: 'answerC',
	},
	{
		id: 69,
		question:
			'W którym filmie bohater używa specjalnie wyćwiczonej techniki marzeń sennych, aby kradnąć tajemnice korporacyjne?',
		answerA: 'Eternal Sunshine of the Spotless Mind',
		answerB: 'Lucy',
		answerC: 'Incepcja',
		answerD: 'Source Code',
		correctAnswer: 'answerC',
	},
	{
		id: 70,
		question: 'Jak nazywa się film o grupie skazańców wysłanej na misję kosmiczną do czarnej dziury?',
		answerA: 'Alien: Covenant',
		answerB: 'Sunshine',
		answerC: 'Interstellar',
		answerD: 'High Life',
		correctAnswer: 'answerD',
	},
	{
		id: 71,
		question:
			'Który film przedstawia historię grupy astronautów próbujących rozbroić bombę na pokładzie statku kosmicznego Icarus II?',
		answerA: 'Prometeusz',
		answerB: 'Sunshine',
		answerC: 'Ad Astra',
		answerD: 'Apollo 13',
		correctAnswer: 'answerB',
	},
	{
		id: 72,
		question: 'W którym filmie rodzina stara się przetrwać w świecie pełnym potworów o nadwrażliwym słuchu?',
		answerA: 'Bird Box',
		answerB: 'Ciche miejsce',
		answerC: 'The Happening',
		answerD: 'War of the Worlds',
		correctAnswer: 'answerB',
	},
	{
		id: 73,
		question: 'Który film opowiada o podróży morskiej młodego chłopca i tygrysa o imieniu Richard Parker?',
		answerA: 'Życie Pi',
		answerB: 'Moby Dick',
		answerC: 'Old Man and the Sea',
		answerD: 'Cast Away',
		correctAnswer: 'answerA',
	},
	{
		id: 74,
		question: 'Jak nazywa się film, w którym grupa przyjaciół próbuje przetrwać noc w mieście pełnym zombie?',
		answerA: '28 dni później',
		answerB: 'World War Z',
		answerC: 'Shaun of the Dead',
		answerD: 'Zombieland',
		correctAnswer: 'answerC',
	},
	{
		id: 75,
		question: 'Który film opowiada o artystce i handlarzu dzieł sztuki, którzy planują kradzież obrazu?',
		answerA: 'Thomas Crown Affair',
		answerB: 'Trick',
		answerC: 'The Italian Job',
		answerD: 'The Art of Stealing',
		correctAnswer: 'answerA',
	},
	{
		id: 76,
		question:
			'Jak nazywa się film, w którym grupa ludzi próbuje przetrwać po globalnej katastrofie, która niemal całkowicie zniszczyła ludzkość i zmusiła ich do życia pod wodą?',
		answerA: 'Deep Blue Sea',
		answerB: 'Waterworld',
		answerC: 'The Abyss',
		answerD: 'Atlantis',
		correctAnswer: 'answerB',
	},
	{
		id: 77,
		question: 'Który film opowiada historię grupy żołnierzy walczących z obcymi podczas inwazji na Ziemię?',
		answerA: 'Starship Troopers',
		answerB: 'Edge of Tomorrow',
		answerC: 'Independence Day',
		answerD: 'War of the Worlds',
		correctAnswer: 'answerA',
	},
	{
		id: 78,
		question: "Kto zagrał główną rolę w filmie 'John Wick'?",
		answerA: 'Jason Statham',
		answerB: 'Keanu Reeves',
		answerC: 'Liam Neeson',
		answerD: 'Bruce Willis',
		correctAnswer: 'answerB',
	},
	{
		id: 79,
		question:
			'W którym filmie młoda kobieta musi przetrwać w świecie, gdzie większość ludzkości została zamieniona w zombie przez grzybową infekcję?',
		answerA: '28 dni później',
		answerB: 'World War Z',
		answerC: 'Resident Evil',
		answerD: 'The Girl with All the Gifts',
		correctAnswer: 'answerD',
	},
	{
		id: 80,
		question:
			'Który film przedstawia historię nastoletniego chłopca, który odkrywa, że jest półbogiem, synem Posejdona?',
		answerA: 'Hercules',
		answerB: 'Percy Jackson & the Olympians: The Lightning Thief',
		answerC: 'Clash of the Titans',
		answerD: 'Immortals',
		correctAnswer: 'answerB',
	},
	{
		id: 81,
		question: 'W którym filmie bogaty ekscentryk zaprasza grupę badaczy na wyspę pełną klonowanych dinozaurów?',
		answerA: 'Godzilla',
		answerB: 'Jurassic Park',
		answerC: 'King Kong',
		answerD: 'The Lost World',
		correctAnswer: 'answerB',
	},
	{
		id: 82,
		question: 'Który film przedstawia podróż astronauty, który zostaje zostawiony na Marsie przez swoją załogę?',
		answerA: 'Interstellar',
		answerB: 'Gravity',
		answerC: 'The Martian',
		answerD: 'Moon',
		correctAnswer: 'answerC',
	},
	{
		id: 83,
		question: 'Który film opowiada o rodzinie superbohaterów, którzy muszą ukrywać swoje moce?',
		answerA: 'The Avengers',
		answerB: 'The Incredibles',
		answerC: 'X-Men',
		answerD: 'Fantastic Four',
		correctAnswer: 'answerB',
	},
	{
		id: 84,
		question: 'Jak nazywa się film, w którym główny bohater budzi się każdego dnia w tym samym dniu?',
		answerA: 'Deja Vu',
		answerB: 'Groundhog Day',
		answerC: 'Looper',
		answerD: "The Time Traveler's Wife",
		correctAnswer: 'answerB',
	},
	{
		id: 85,
		question:
			'Który film przedstawia historię matematyka, który próbuje przewidzieć rynkowe trendy za pomocą skomplikowanego systemu?',
		answerA: 'A Beautiful Mind',
		answerB: 'The Imitation Game',
		answerC: 'Moneyball',
		answerD: 'Pi',
		correctAnswer: 'answerD',
	},
	{
		id: 86,
		question:
			'Który film opowiada historię grupy ludzi, którzy wpadają w śpiączkę i wędrują do wspólnej świadomości snów?',
		answerA: 'Inception',
		answerB: 'The Cell',
		answerC: 'Paprika',
		answerD: 'The Science of Sleep',
		correctAnswer: 'answerC',
	},
	{
		id: 87,
		question: 'W którym filmie robot o imieniu WALL-E zakochuje się w innym robocie o nazwie EVE?',
		answerA: 'Robots',
		answerB: 'I, Robot',
		answerC: 'WALL-E',
		answerD: 'Short Circuit',
		correctAnswer: 'answerC',
	},
	{
		id: 88,
		question:
			'Który film opowiada historię królowej Szkocji, Maria Stuart, i jej politycznej rywalizacji z królową Anglii, Elżbietą I?',
		answerA: 'Elizabeth',
		answerB: 'Mary Queen of Scots',
		answerC: 'The Other Boleyn Girl',
		answerD: 'The Favourite',
		correctAnswer: 'answerB',
	},
	{
		id: 89,
		question:
			'W którym filmie kierowca wyścigowy i konstruktor samochodowy łączą siły, aby pokonać dominujące włoskie firmy samochodowe?',
		answerA: 'Rush',
		answerB: 'Ford v Ferrari',
		answerC: 'Talladega Nights',
		answerD: 'Days of Thunder',
		correctAnswer: 'answerB',
	},
	{
		id: 90,
		question:
			'Jak nazywa się film, w którym młody mężczyzna odkrywa, że jego ojciec, którego nigdy nie poznał, jest bogatym przedsiębiorcą?',
		answerA: 'The Pursuit of Happyness',
		answerB: 'The Secret Life of Walter Mitty',
		answerC: 'Big Fish',
		answerD: 'About a Boy',
		correctAnswer: 'answerC',
	},
]

const questionsMusic = [
	{
		id: 91,
		question: 'Kto jest kompozytorem utworu "Dla Elizy"?',
		answerA: 'Wolfgang Amadeus Mozart',
		answerB: 'Johannes Brahms',
		answerC: 'Ludwig van Beethoven',
		answerD: 'Franz Schubert',
		correctAnswer: 'answerC',
	},
	{
		id: 92,
		question: 'Który zespół nagrał piosenkę "Bohemian Rhapsody"?',
		answerA: 'The Beatles',
		answerB: 'Led Zeppelin',
		answerC: 'Pink Floyd',
		answerD: 'Queen',
		correctAnswer: 'answerD',
	},
	{
		id: 93,
		question: 'Który instrument muzyczny nie należy do rodziny instrumentów dętych?',
		answerA: 'Flet',
		answerB: 'Trąbka',
		answerC: 'Skrzypce',
		answerD: 'Saksofon',
		correctAnswer: 'answerC',
	},
	{
		id: 94,
		question: 'Kto jest autorem "Czterech Pór Roku"?',
		answerA: 'Antonio Vivaldi',
		answerB: 'Johann Sebastian Bach',
		answerC: 'Wolfgang Amadeus Mozart',
		answerD: 'Ludwig van Beethoven',
		correctAnswer: 'answerA',
	},
	{
		id: 95,
		question: 'Która piosenkarka jest znana jako "Królowa Popu"?',
		answerA: 'Beyoncé',
		answerB: 'Madonna',
		answerC: 'Britney Spears',
		answerD: 'Whitney Houston',
		correctAnswer: 'answerB',
	},
	{
		id: 96,
		question: 'Który zespół jest autorem albumu "The Dark Side of the Moon"?',
		answerA: 'The Rolling Stones',
		answerB: 'The Beatles',
		answerC: 'Pink Floyd',
		answerD: 'The Doors',
		correctAnswer: 'answerC',
	},
	{
		id: 97,
		question: 'W którym kraju narodziła się bossa nova?',
		answerA: 'Hiszpania',
		answerB: 'Kuba',
		answerC: 'Meksyk',
		answerD: 'Brazylia',
		correctAnswer: 'answerD',
	},
	{
		id: 98,
		question: 'Kto jest kompozytorem opery "Carmen"?',
		answerA: 'Giuseppe Verdi',
		answerB: 'Gioachino Rossini',
		answerC: 'Georges Bizet',
		answerD: 'Richard Wagner',
		correctAnswer: 'answerC',
	},
	{
		id: 99,
		question: 'Jak nazywa się gatunek muzyczny, który pochodzi z Jamajki i jest poprzednikiem reggae?',
		answerA: 'Rumba',
		answerB: 'Ska',
		answerC: 'Calypso',
		answerD: 'Mento',
		correctAnswer: 'answerB',
	},
	{
		id: 100,
		question: 'Kto śpiewa piosenkę "Imagine"?',
		answerA: 'Paul McCartney',
		answerB: 'Elton John',
		answerC: 'John Lennon',
		answerD: 'Bob Dylan',
		correctAnswer: 'answerC',
	},
	{
		id: 101,
		question: 'Kto jest autorem albumu "Thriller"?',
		answerA: 'Michael Jackson',
		answerB: 'Prince',
		answerC: 'Stevie Wonder',
		answerD: 'George Michael',
		correctAnswer: 'answerA',
	},
	{
		id: 102,
		question: 'Który z tych instrumentów jest instrumentem perkusyjnym?',
		answerA: 'Gitara',
		answerB: 'Fagot',
		answerC: 'Harfa',
		answerD: 'Bęben',
		correctAnswer: 'answerD',
	},
	{
		id: 103,
		question: 'Kto napisał "Pieśń o Rolandzie" - średniowieczną epopeję?',
		answerA: 'Hildegarda z Bingen',
		answerB: 'Wolfram von Eschenbach',
		answerC: 'Nieznany',
		answerD: 'Adam z Paryża',
		correctAnswer: 'answerC',
	},
	{
		id: 104,
		question: 'Który zespół wydał album "Achtung Baby"?',
		answerA: 'Coldplay',
		answerB: 'U2',
		answerC: 'The Police',
		answerD: 'REM',
		correctAnswer: 'answerB',
	},
	{
		id: 105,
		question: 'Która z tych piosenek jest autorstwa The Beatles?',
		answerA: 'Paint It Black',
		answerB: 'Stairway to Heaven',
		answerC: 'Hey Jude',
		answerD: 'Hotel California',
		correctAnswer: 'answerC',
	},
	{
		id: 106,
		question: 'Kto jest uważany za "Króla Rock and Rolla"?',
		answerA: 'Elvis Presley',
		answerB: 'Chuck Berry',
		answerC: 'Buddy Holly',
		answerD: 'Jerry Lee Lewis',
		correctAnswer: 'answerA',
	},
	{
		id: 107,
		question: 'Który instrument jest charakterystyczny dla flamenco?',
		answerA: 'Akordeon',
		answerB: 'Gitara',
		answerC: 'Saksofon',
		answerD: 'Trąbka',
		correctAnswer: 'answerB',
	},
	{
		id: 108,
		question: 'Która piosenkarka zaśpiewała główny temat w filmie "Titanic"?',
		answerA: 'Mariah Carey',
		answerB: 'Whitney Houston',
		answerC: 'Celine Dion',
		answerD: 'Shania Twain',
		correctAnswer: 'answerC',
	},
	{
		id: 109,
		question: 'Która z tych form muzycznych jest typowa dla opery?',
		answerA: 'Sonata',
		answerB: 'Ballada',
		answerC: 'Aria',
		answerD: 'Etuda',
		correctAnswer: 'answerC',
	},
	{
		id: 110,
		question: 'Który z tych kompozytorów jest uważany za twórcę opery "Don Giovanni"?',
		answerA: 'Richard Strauss',
		answerB: 'Wolfgang Amadeus Mozart',
		answerC: 'Giacomo Puccini',
		answerD: 'Georg Friedrich Händel',
		correctAnswer: 'answerB',
	},
	{
		id: 111,
		question: 'Który kompozytor jest znany z "Kanonu w D-dur"?',
		answerA: 'Antonín Dvořák',
		answerB: 'Johannes Brahms',
		answerC: 'Johann Pachelbel',
		answerD: 'Franz Liszt',
		correctAnswer: 'answerC',
	},
	{
		id: 112,
		question: 'Która z tych grup jest twórcą albumu "OK Computer"?',
		answerA: 'Oasis',
		answerB: 'Blur',
		answerC: 'Radiohead',
		answerD: 'Coldplay',
		correctAnswer: 'answerC',
	},
	{
		id: 113,
		question: 'Który instrument jest uważany za najstarszy na świecie?',
		answerA: 'Bęben',
		answerB: 'Flet',
		answerC: 'Lira',
		answerD: 'Tamburyn',
		correctAnswer: 'answerB',
	},
	{
		id: 114,
		question: 'Jak nazywa się artysta założyciel zespołu Ziggy Stardust?',
		answerA: 'Freddie Mercury',
		answerB: 'Mick Jagger',
		answerC: 'Robert Plant',
		answerD: 'David Bowie',
		correctAnswer: 'answerD',
	},
	{
		id: 115,
		question: 'Która z tych skrzypaczek jest znana z gry na elektrycznych skrzypcach?',
		answerA: 'Hilary Hahn',
		answerB: 'Anne-Sophie Mutter',
		answerC: 'Lindsey Stirling',
		answerD: 'Itzhak Perlman',
		correctAnswer: 'answerC',
	},
	{
		id: 116,
		question: 'Który zespół nagrał piosenkę "Hotel California"?',
		answerA: 'The Rolling Stones',
		answerB: 'The Beatles',
		answerC: 'The Eagles',
		answerD: 'Fleetwood Mac',
		correctAnswer: 'answerC',
	},
	{
		id: 117,
		question: 'Kto jest autorem klasycznej kompozycji "Bolero"?',
		answerA: 'Maurice Ravel',
		answerB: 'Igor Strawiński',
		answerC: 'Ludwig van Beethoven',
		answerD: 'Johann Sebastian Bach',
		correctAnswer: 'answerA',
	},
	{
		id: 118,
		question: 'Która piosenkarka jest znana z hitu "Like a Virgin"?',
		answerA: 'Cyndi Lauper',
		answerB: 'Madonna',
		answerC: 'Whitney Houston',
		answerD: 'Cher',
		correctAnswer: 'answerB',
	},
	{
		id: 119,
		question: 'Która z tych form muzycznych jest typowa dla muzyki jazzowej?',
		answerA: 'Minuet',
		answerB: 'Sonatina',
		answerC: 'Fuga',
		answerD: 'Improwizacja',
		correctAnswer: 'answerD',
	},
	{
		id: 120,
		question: 'Który z tych kompozytorów jest uważany za twórcę "Symfonii Heroicznej"?',
		answerA: 'Joseph Haydn',
		answerB: 'Franz Schubert',
		answerC: 'Wolfgang Amadeus Mozart',
		answerD: 'Ludwig van Beethoven',
		correctAnswer: 'answerD',
	},
	{
		id: 121,
		question: 'Który z tych artystów nie należy do "Wielkiej Czwórki" thrash metalu?',
		answerA: 'Metallica',
		answerB: 'Megadeth',
		answerC: 'Slayer',
		answerD: 'Iron Maiden',
		correctAnswer: 'answerD',
	},
	{
		id: 122,
		question: 'Jak nazywa się klasyczny taniec hiszpański, który charakteryzuje się mocnym stukaniem butami?',
		answerA: 'Samba',
		answerB: 'Flamenco',
		answerC: 'Tango',
		answerD: 'Rumba',
		correctAnswer: 'answerB',
	},
	{
		id: 123,
		question: 'Który z tych instrumentów nie jest strunowy?',
		answerA: 'Wiolonczela',
		answerB: 'Fagot',
		answerC: 'Kontrabas',
		answerD: 'Harfa',
		correctAnswer: 'answerB',
	},
	{
		id: 124,
		question: 'Kto jest autorem albumu "Born in the U.S.A."?',
		answerA: 'Bob Dylan',
		answerB: 'Bruce Springsteen',
		answerC: 'John Mellencamp',
		answerD: 'Tom Petty',
		correctAnswer: 'answerB',
	},
	{
		id: 125,
		question: 'Który z tych zespołów pochodzi z Australii?',
		answerA: 'AC/DC',
		answerB: 'Aerosmith',
		answerC: 'The Rolling Stones',
		answerD: `Guns N' Roses`,
		correctAnswer: 'answerA',
	},
	{
		id: 126,
		question: 'Który kompozytor jest znany z opery "Czarodziejski flet"?',
		answerA: 'Giuseppe Verdi',
		answerB: 'Wolfgang Amadeus Mozart',
		answerC: 'Richard Wagner',
		answerD: 'Gioachino Rossini',
		correctAnswer: 'answerB',
	},
	{
		id: 127,
		question: 'Która z tych piosenek nie jest autorstwa The Beatles?',
		answerA: 'Let It Be',
		answerB: `(I Can't Get No) Satisfaction`,
		answerC: 'Yesterday',
		answerD: 'Come Together',
		correctAnswer: 'answerB',
	},
	{
		id: 128,
		question: 'Który instrument jest charakterystyczny dla muzyki reggae?',
		answerA: 'Elektryczna gitara',
		answerB: 'Organy Hammonda',
		answerC: 'Syntezator',
		answerD: 'Bębenek jamajski',
		correctAnswer: 'answerD',
	},
	{
		id: 129,
		question: 'Który z tych artystów jest uważany za "Boga Gitary"?',
		answerA: 'Eric Clapton',
		answerB: 'Jimi Hendrix',
		answerC: 'Keith Richards',
		answerD: 'Brian May',
		correctAnswer: 'answerA',
	},
	{
		id: 130,
		question: 'Kto jest autorem albumu "Purple Rain"?',
		answerA: 'Michael Jackson',
		answerB: 'Prince',
		answerC: 'Lenny Kravitz',
		answerD: 'Lionel Richie',
		correctAnswer: 'answerB',
	},
	{
		id: 131,
		question: 'Która z tych piosenek była hitem Whitney Houston z filmu "Bodyguard"?',
		answerA: 'Vision of Love',
		answerB: 'Respect',
		answerC: 'I Will Always Love You',
		answerD: 'Endless Love',
		correctAnswer: 'answerC',
	},
	{
		id: 132,
		question: 'Kto jest kompozytorem suity "Planety"?',
		answerA: 'Benjamin Britten',
		answerB: 'Gustav Holst',
		answerC: 'Aaron Copland',
		answerD: 'Richard Strauss',
		correctAnswer: 'answerB',
	},
	{
		id: 133,
		question: 'Która z tych grup jest twórcą albumu "The Wall"?',
		answerA: 'The Who',
		answerB: 'Pink Floyd',
		answerC: 'Led Zeppelin',
		answerD: 'The Rolling Stones',
		correctAnswer: 'answerB',
	},
	{
		id: 134,
		question: 'Który z tych instrumentów jest instrumentem dętym drewnianym?',
		answerA: 'Trombon',
		answerB: 'Trąbka',
		answerC: 'Oboj',
		answerD: 'Puzon',
		correctAnswer: 'answerC',
	},
	{
		id: 135,
		question: 'Który z tych artystów jest związany z gatunkiem grunge?',
		answerA: 'Kurt Cobain',
		answerB: 'Elton John',
		answerC: 'Freddie Mercury',
		answerD: 'Bob Marley',
		correctAnswer: 'answerA',
	},
	{
		id: 136,
		question: 'Kto jest autorem słynnej "Sonaty Księżycowej"?',
		answerA: 'Johann Sebastian Bach',
		answerB: 'Wolfgang Amadeus Mozart',
		answerC: 'Franz Schubert',
		answerD: 'Ludwig van Beethoven',
		correctAnswer: 'answerD',
	},
	{
		id: 137,
		question: 'Która z tych piosenek jest hitem zespołu ABBA?',
		answerA: 'Stayin’ Alive',
		answerB: 'Dancing Queen',
		answerC: 'Like a Prayer',
		answerD: 'Billie Jean',
		correctAnswer: 'answerB',
	},
	{
		id: 138,
		question: 'Który z tych instrumentów jest tradycyjnie używany w muzyce klezmerskiej?',
		answerA: 'Dudy',
		answerB: 'Akordeon',
		answerC: 'Klarnet',
		answerD: 'Flet prosty',
		correctAnswer: 'answerC',
	},
	{
		id: 139,
		question: 'Który z tych artystów jest znany jako "The Boss"?',
		answerA: 'Bruce Springsteen',
		answerB: 'Billy Joel',
		answerC: 'Elton John',
		answerD: 'Paul McCartney',
		correctAnswer: 'answerA',
	},
	{
		id: 140,
		question: 'Który kompozytor jest twórcą opery "Carmen"?',
		answerA: 'Giuseppe Verdi',
		answerB: 'Wolfgang Amadeus Mozart',
		answerC: 'Georges Bizet',
		answerD: 'Giacomo Puccini',
		correctAnswer: 'answerC',
	},
	{
		id: 141,
		question: 'Która piosenkarka jest znana z hitu "Single Ladies"?',
		answerA: 'Beyoncé',
		answerB: 'Rihanna',
		answerC: 'Alicia Keys',
		answerD: 'Adele',
		correctAnswer: 'answerA',
	},
	{
		id: 142,
		question: 'Kto jest kompozytorem suity "Dziecięcego karnawału"?',
		answerA: 'Claude Debussy',
		answerB: 'Maurice Ravel',
		answerC: 'Sergei Prokofiev',
		answerD: 'Camille Saint-Saëns',
		correctAnswer: 'answerD',
	},
	{
		id: 143,
		question: 'Która z tych grup jest autorem piosenki "Bohemian Rhapsody"?',
		answerA: 'The Beatles',
		answerB: 'Rolling Stones',
		answerC: 'Deep Purple',
		answerD: 'Queen',
		correctAnswer: 'answerD',
	},
	{
		id: 144,
		question: 'Jaką nazwę nosi tradycyjny bęben japoński?',
		answerA: 'Sitar',
		answerB: 'Taiko',
		answerC: 'Erhu',
		answerD: 'Didgeridoo',
		correctAnswer: 'answerB',
	},
	{
		id: 145,
		question: 'Który z tych artystów jest uważany za króla popu?',
		answerA: 'Prince',
		answerB: 'Elvis Presley',
		answerC: 'Michael Jackson',
		answerD: 'Madonna',
		correctAnswer: 'answerC',
	},
	{
		id: 146,
		question: 'Kto jest autorem klasycznej kompozycji "Cztery pory roku"?',
		answerA: 'Antonio Vivaldi',
		answerB: 'Ludwig van Beethoven',
		answerC: 'Franz Joseph Haydn',
		answerD: 'Johannes Brahms',
		correctAnswer: 'answerA',
	},
	{
		id: 147,
		question: 'Który z tych zespołów pochodzi z Irlandii?',
		answerA: 'Coldplay',
		answerB: 'U2',
		answerC: 'Oasis',
		answerD: 'Arctic Monkeys',
		correctAnswer: 'answerB',
	},
	{
		id: 148,
		question: 'Który instrument jest charakterystyczny dla muzyki bluegrass?',
		answerA: 'Harmonijka ustna',
		answerB: 'Banjo',
		answerC: 'Saksofon',
		answerD: 'Flet',
		correctAnswer: 'answerB',
	},
	{
		id: 149,
		question: 'Który z tych artystów jest znany z piosenki "Purple Haze"?',
		answerA: 'Eric Clapton',
		answerB: 'Jimi Hendrix',
		answerC: 'Bob Dylan',
		answerD: 'B.B. King',
		correctAnswer: 'answerB',
	},
	{
		id: 150,
		question: 'Która z tych artystek jest znana jako "Królowa Soul"?',
		answerA: 'Diana Ross',
		answerB: 'Whitney Houston',
		answerC: 'Aretha Franklin',
		answerD: 'Tina Turner',
		correctAnswer: 'answerC',
	},
	{
		id: 151,
		question: 'Który z tych zespołów nagrał album "Dark Side of the Moon"?',
		answerA: 'The Beatles',
		answerB: 'Pink Floyd',
		answerC: 'The Doors',
		answerD: 'The Who',
		correctAnswer: 'answerB',
	},
	{
		id: 152,
		question: 'Kto jest kompozytorem słynnego "Jeziora łabędziego"?',
		answerA: 'Piotr Czajkowski',
		answerB: 'Johannes Brahms',
		answerC: 'Igor Strawinski',
		answerD: 'Franz Schubert',
		correctAnswer: 'answerA',
	},
	{
		id: 153,
		question: 'Która piosenkarka wydała album zatytułowany "Lemonade"?',
		answerA: 'Taylor Swift',
		answerB: 'Ariana Grande',
		answerC: 'Katy Perry',
		answerD: 'Beyoncé',
		correctAnswer: 'answerD',
	},
	{
		id: 154,
		question: 'Który instrument muzyczny jest głównym w orkiestrze dętej?',
		answerA: 'Wiolonczela',
		answerB: 'Saksofon',
		answerC: 'Gitara elektryczna',
		answerD: 'Bęben',
		correctAnswer: 'answerB',
	},
	{
		id: 155,
		question: 'Która z tych grup jest autorem piosenki "Hotel California"?',
		answerA: 'Led Zeppelin',
		answerB: 'The Eagles',
		answerC: 'Lynyrd Skynyrd',
		answerD: 'The Rolling Stones',
		correctAnswer: 'answerB',
	},
	{
		id: 156,
		question: 'Kto jest autorem opery "Aida"?',
		answerA: 'Wolfgang Amadeus Mozart',
		answerB: 'Giuseppe Verdi',
		answerC: 'Richard Wagner',
		answerD: 'George Frideric Handel',
		correctAnswer: 'answerB',
	},
	{
		id: 157,
		question: 'Jak nazywa się instrument klawiszowy, który używa powietrza do wydobywania dźwięku?',
		answerA: 'Pianino',
		answerB: 'Klawesyn',
		answerC: 'Organy',
		answerD: 'Cembalo',
		correctAnswer: 'answerC',
	},
	{
		id: 158,
		question: 'Która z tych piosenek nie jest autorstwa Davida Bowiego?',
		answerA: 'Heroes',
		answerB: 'Life on Mars?',
		answerC: 'Imagine',
		answerD: 'Space Oddity',
		correctAnswer: 'answerC',
	},
	{
		id: 159,
		question: 'Który artysta jest znany z piosenki "Like a Rolling Stone"?',
		answerA: 'Bob Dylan',
		answerB: 'Paul Simon',
		answerC: 'Jimi Hendrix',
		answerD: 'Neil Young',
		correctAnswer: 'answerA',
	},
	{
		id: 160,
		question: 'Kto jest autorem albumu "Thriller"?',
		answerA: 'Michael Jackson',
		answerB: 'Prince',
		answerC: 'Madonna',
		answerD: 'Elvis Presley',
		correctAnswer: 'answerA',
	},
	{
		id: 161,
		question: 'Który z tych zespołów nagrał piosenkę "Smells Like Teen Spirit"?',
		answerA: 'Nirvana',
		answerB: 'Radiohead',
		answerC: 'Red Hot Chili Peppers',
		answerD: 'Pearl Jam',
		correctAnswer: 'answerA',
	},
	{
		id: 162,
		question: 'Który kompozytor stworzył "Boléro"?',
		answerA: 'Claude Debussy',
		answerB: 'Johann Strauss II',
		answerC: 'Ludwig van Beethoven',
		answerD: 'Maurice Ravel',
		correctAnswer: 'answerD',
	},
	{
		id: 163,
		question: 'Która piosenkarka jest znana z hitu "Like a Virgin"?',
		answerA: 'Cyndi Lauper',
		answerB: 'Madonna',
		answerC: 'Britney Spears',
		answerD: 'Janet Jackson',
		correctAnswer: 'answerB',
	},
	{
		id: 164,
		question: 'Który instrument jest głównym składnikiem orkiestry smyczkowej?',
		answerA: 'Saksofon',
		answerB: 'Skrzypce',
		answerC: 'Gitara',
		answerD: 'Trąbka',
		correctAnswer: 'answerB',
	},
	{
		id: 165,
		question: 'Który z tych zespołów wydał album "OK Computer"?',
		answerA: 'Oasis',
		answerB: 'Blur',
		answerC: 'Coldplay',
		answerD: 'Radiohead',
		correctAnswer: 'answerD',
	},
	{
		id: 166,
		question: 'Kto jest autorem opery "Don Giovanni"?',
		answerA: 'Gioachino Rossini',
		answerB: 'Wolfgang Amadeus Mozart',
		answerC: 'Giuseppe Verdi',
		answerD: 'Richard Wagner',
		correctAnswer: 'answerB',
	},
	{
		id: 167,
		question: 'Jak nazywa się duży instrument klawiszowy z czarnymi i białymi klawiszami?',
		answerA: 'Harfa',
		answerB: 'Pianino',
		answerC: 'Klawesyn',
		answerD: 'Akordeon',
		correctAnswer: 'answerB',
	},
	{
		id: 168,
		question: 'Która z tych piosenek jest autorstwa The Beatles?',
		answerA: 'Paint It Black',
		answerB: 'Gimme Shelter',
		answerC: 'Hey Jude',
		answerD: 'Angie',
		correctAnswer: 'answerC',
	},
	{
		id: 169,
		question: 'Który artysta jest znany z piosenki "Superstition"?',
		answerA: 'James Brown',
		answerB: 'Stevie Wonder',
		answerC: 'Marvin Gaye',
		answerD: 'Ray Charles',
		correctAnswer: 'answerB',
	},
	{
		id: 170,
		question: 'Kto jest autorem albumu "Born in the U.S.A."?',
		answerA: 'John Mellencamp',
		answerB: 'Tom Petty',
		answerC: 'Bruce Springsteen',
		answerD: 'Billy Joel',
		correctAnswer: 'answerC',
	},
	{
		id: 171,
		question: 'Który z tych zespołów jest związany z piosenką "Stairway to Heaven"?',
		answerA: 'The Rolling Stones',
		answerB: 'Led Zeppelin',
		answerC: 'Black Sabbath',
		answerD: 'Aerosmith',
		correctAnswer: 'answerB',
	},
	{
		id: 172,
		question: 'Który kompozytor stworzył symfonię "Niedokończona"?',
		answerA: 'Franz Schubert',
		answerB: 'Johannes Brahms',
		answerC: 'Ludwig van Beethoven',
		answerD: 'Wolfgang Amadeus Mozart',
		correctAnswer: 'answerA',
	},
	{
		id: 173,
		question: 'Która piosenkarka jest znana z albumu "Back to Black"?',
		answerA: 'Amy Winehouse',
		answerB: 'Adele',
		answerC: 'Lana Del Rey',
		answerD: 'Duffy',
		correctAnswer: 'answerA',
	},
	{
		id: 174,
		question: 'Który instrument jest charakterystyczny dla muzyki reggae?',
		answerA: 'Gitara basowa',
		answerB: 'Sitar',
		answerC: 'Bębenek',
		answerD: 'Dudelsack',
		correctAnswer: 'answerA',
	},
	{
		id: 175,
		question: 'Który z tych zespołów wydał album "Achtung Baby"?',
		answerA: 'U2',
		answerB: 'REM',
		answerC: 'The Cure',
		answerD: 'Depeche Mode',
		correctAnswer: 'answerA',
	},
	{
		id: 176,
		question: 'Który z kompozytorów jest twórcą "Rapsodii w niebieskim"?',
		answerA: 'Leonard Bernstein',
		answerB: 'Dmitri Shostakovich',
		answerC: 'George Gershwin',
		answerD: 'Igor Stravinsky',
		correctAnswer: 'answerC',
	},
	{
		id: 177,
		question: 'Jak nazywa się instrument perkusyjny w kształcie litery X, na którym uderza się pałeczkami?',
		answerA: 'Xylofon',
		answerB: 'Marimba',
		answerC: 'Wibrafon',
		answerD: 'Gong',
		correctAnswer: 'answerA',
	},
	{
		id: 178,
		question: 'Który z tych artystów śpiewał piosenkę "Hound Dog"?',
		answerA: 'Buddy Holly',
		answerB: 'Chuck Berry',
		answerC: 'Jerry Lee Lewis',
		answerD: 'Elvis Presley',
		correctAnswer: 'answerD',
	},
	{
		id: 179,
		question: 'Która z tych artystek nagrała hit "I Will Always Love You" dla filmu "The Bodyguard"?',
		answerA: 'Mariah Carey',
		answerB: 'Whitney Houston',
		answerC: 'Celine Dion',
		answerD: 'Barbra Streisand',
		correctAnswer: 'answerB',
	},
	{
		id: 180,
		question: 'Który z tych zespołów pochodzi z Australii?',
		answerA: 'AC/DC',
		answerB: 'Metallica',
		answerC: 'Iron Maiden',
		answerD: 'Nirvana',
		correctAnswer: 'answerA',
	},
]
